<?php

declare(strict_types=1);

namespace MyInvoice\Service\Anonymization;

/**
 * Rozhodnutí pro KAŽDÝ textový sloupec databáze: pseudonymizovat, jak, nebo ponechat.
 *
 * Architektonický test (`AnonymizationPolicyCoverageTest`) porovnává tenhle seznam
 * s otiskem struktury `db/schema.snapshot.json`. Nová tabulka nebo nový textový
 * sloupec bez rozhodnutí test shodí — anonymizovaná kopie tak nemůže tiše nést
 * osobní údaje z tabulky, na kterou se zapomnělo.
 *
 * Strategie sloupce:
 *  - `keep`          bez osobních údajů (kódy, číselníky, otisky, technické klíče)
 *  - `text` / `json` volný text nebo JSON — slovník pseudonymů + vzory (e-mail,
 *                    účet, IBAN, RČ, DIČ, IČO, telefon), viz {@see TextScrubber}
 *  - `party_name`, `person_name`, `first_name`, `last_name`, `street`, `city`,
 *    `zip`, `address`, `ico`, `dic`, `birth_number`, `email`, `phone`,
 *    `bank_account`, `iban`, `card_last4`, `data_box`, `web`, `host`, `login`,
 *    `shape`, `shape_digits`, `file_name`, `file_path` — viz {@see Pseudonymizer}
 *  - `account_key`   odvozený klíč účtu (jen číslice) — týž pseudonym jako účet
 *  - `symbol`        VS/SS: změní se jen, je-li celý symbol pseudonymizovaný
 *                    identifikátor (IČO, RČ, účet); čísla faktur zůstanou
 *  - `wipe`          tajemství, šifrované archivy, tokeny, IP adresy — NULL
 *                    (u NOT NULL prázdná hodnota, u JSON `{}`)
 *  - `token`         náhodný nový token stejné délky (unikátní odkazy)
 *  - `password`      nepoužitelný hash hesla (nové heslo nastaví `set-password.php`)
 *  - `blob_pdf` / `blob_text` obsah souboru v databázi → zástupný soubor
 *  - `sealed:<pole|@sloupec typu>:<hash>:<maska|->:<entita>` šifrovaná mzdová
 *                    hodnota: dešifrovat, pseudonymizovat, znovu zapečetit
 *  - `sealed_companion` otisk/maska patřící k `sealed` sloupci téže tabulky
 */
final class AnonymizationPolicy
{
    /**
     * Tabulky, které se v kopii vyprázdní — přihlášení, relace, tokeny, fronty
     * odchozí pošty, cache registrů a vektorové indexy obsahu dokumentů. Pro
     * testovací instanci nemají hodnotu a obsahují osobní údaje nebo tajemství.
     *
     * @var array<string,string> tabulka → důvod
     */
    public const TRUNCATE = [
        'abra_flexi_connections' => 'šifrované připojení ke zdrojové účetní firmě',
        'ai_embeddings' => 'vektory z textů skutečných dokladů; naučí se znovu',
        'api_request_log' => 'IP adresy a dotazy klientů API',
        'api_token_ips' => 'patří k API tokenům',
        'api_tokens' => 'přístupové tokeny instance',
        'ares_cache' => 'cache registru ARES',
        'bank_connector_cooldowns' => 'otisky přístupových údajů k bance',
        'bank_oauth_sessions' => 'rozpracované OAuth relace s bankou',
        'crpdph_cache' => 'cache registru plátců DPH',
        'document_embeddings' => 'úryvky obsahu skutečných dokumentů',
        'instance_exports' => 'odkazy na exportní archivy originální instance',
        'isds_gateway_sessions' => 'relace odesílací brány ISDS',
        'license' => 'licence patří originální instanci; kopie se aktivuje zvlášť',
        'login_attempts' => 'e-maily a IP adresy pokusů o přihlášení',
        'login_otps' => 'jednorázové kódy',
        'mail_outbox' => 'fronta odchozí pošty — v kopii se nic odeslat nesmí',
        'mail_rate_limit_events' => 'technický záznam odesílání',
        'mcp_oauth_clients' => 'registrace externích MCP klientů',
        'mcp_oauth_codes' => 'jednorázové autorizační kódy',
        'mcp_oauth_grants' => 'obnovovací tokeny externích MCP klientů',
        'mfa_recovery_codes' => 'záchranné kódy 2FA',
        'mfa_step_up_proofs' => 'doklady o ověření relace',
        'password_resets' => 'tokeny pro obnovu hesla',
        'payroll_document_access_codes' => 'přístupové kódy zaměstnanců k dokumentům',
        'payroll_document_access_links' => 'odkazy zaslané zaměstnancům',
        'payroll_document_access_sessions' => 'relace zaměstnanců',
        'payroll_document_download_grants' => 'jednorázová oprávnění ke stažení',
        'payroll_payment_export_download_grants' => 'jednorázová oprávnění ke stažení',
        'payroll_period_export_download_grants' => 'jednorázová oprávnění ke stažení',
        'payroll_submission_artifact_download_grants' => 'jednorázová oprávnění ke stažení',
        'rate_limit_counters' => 'technické čítače s IP adresami',
        'sessions' => 'přihlášené relace',
        'submission_isds_auth_flows' => 'rozpracované přihlášení do ISDS',
        'supplier_domain_login_requests' => 'rozpracovaná přihlášení přes doménu',
        'totp_used_steps' => 'použité kroky TOTP',
        'trusted_devices' => 'důvěryhodná zařízení uživatelů',
        'vies_cache' => 'cache registru VIES',
        'webauthn_ceremonies' => 'rozpracované ověření klíčem',
        'webauthn_credentials' => 'bezpečnostní klíče uživatelů',
        'work_report_link_codes' => 'přístupové kódy klientů k výkazům',
        'work_report_link_sessions' => 'relace klientů k výkazům',
    ];

    /**
     * Sloupce, které se zkopírují, ale obsahují tajemství nebo odkazují na
     * odchozí integraci — po pseudonymizaci se integrace vypnou, aby kopie
     * nikam nic neposlala (banka, e-mail, ISDS, e-shop).
     *
     * @var list<string>
     */
    public const POST_SQL = [
        'UPDATE bank_connections SET enabled = 0',
        'UPDATE bank_email_imap_settings SET enabled = 0',
        'UPDATE email_profiles SET is_active = 0',
        "UPDATE integration_connections SET status = 'paused' WHERE status = 'active'",
        'UPDATE submission_channel_credentials SET inbox_polling_enabled = 0',
        'UPDATE isds_gateway_registrations SET is_active = 0',
        'UPDATE mcp_server_settings SET enabled = 0',
        'UPDATE users SET totp_enabled = 0',
    ];

    /**
     * Veřejné účty institucí a platebních bran — zůstávají, aby aplikace
     * dál rozpoznala platby finančnímu úřadu, ČSSZ či výplaty brány.
     * Účty institucí ve mzdách jsou šifrované; dešifruje je služba.
     *
     * @var list<string> SELECT vracející sloupec `account`
     */
    public const PRESERVED_ACCOUNT_SQL = [
        "SELECT CONCAT(IF(COALESCE(account_prefix, '') = '', '', CONCAT(account_prefix, '-')), account_number, '/', bank_code) AS account FROM remittance_map WHERE account_number IS NOT NULL AND account_number <> ''",
        "SELECT CONCAT(payout_account_number, '/', payout_bank_code) AS account FROM gopay_settings WHERE payout_account_number IS NOT NULL AND payout_account_number <> ''",
    ];

    /** @var array<string, array<string,string>> */
    public const COLUMNS = [
        'accounting_archives' => ['filename' => 'file_path', 'scope' => 'keep', 'sha256' => 'keep'],
        'accounting_backfill_jobs' => ['last_error' => 'text', 'log_text' => 'text', 'params' => 'json', 'report_json' => 'json'],
        'accounting_balance_inventory' => ['note' => 'text', 'protocol_ref' => 'text', 'responsible_person' => 'person_name'],
        'accounting_balance_inventory_items' => ['account_code' => 'keep', 'note' => 'text'],
        'accounting_closing_steps' => ['note' => 'text', 'payload' => 'json'],
        'accounting_corrections' => ['final_credit' => 'keep', 'final_debit' => 'keep', 'model' => 'keep', 'prompt_version' => 'keep', 'reason' => 'text', 'suggested_credit' => 'keep', 'suggested_debit' => 'keep'],
        'accounting_document_series' => ['number_format' => 'keep', 'prefix' => 'keep'],
        'accounting_fixed_exchange_rates' => ['currency_code' => 'keep'],
        'accounting_opening_balances' => ['account_code' => 'keep', 'note' => 'text'],
        'accounting_periods' => ['approval_body' => 'text', 'approval_decision_ref' => 'text', 'approval_document_hash' => 'keep', 'created_reason' => 'keep'],
        'accounting_reclassification_items' => ['after_json' => 'json', 'before_json' => 'json', 'error_code' => 'keep', 'error_message' => 'text'],
        'accounting_setup_proposals' => ['evidence_json' => 'json', 'proposal_json' => 'json', 'signature' => 'keep', 'title' => 'text'],
        'accounting_setup_rule_bundles' => ['bundle_hash' => 'keep', 'input_hash' => 'keep', 'payload_json' => 'json'],
        'accounting_setup_runs' => ['chart_hash' => 'keep', 'input_hash' => 'keep', 'rules_hash' => 'keep', 'scope_json' => 'json', 'summary_json' => 'json'],
        'accounting_supplier_settings' => ['fuel_account_code' => 'keep', 'net_turnover_extra_rows' => 'json', 'vehicle_repair_account_code' => 'keep'],
        'activity_log' => ['action' => 'keep', 'entity_type' => 'keep', 'hash' => 'keep', 'ip' => 'wipe', 'payload' => 'json', 'prev_hash' => 'keep', 'user_agent' => 'wipe'],
        'activity_log_chain_head' => ['last_hash' => 'keep'],
        'ai_jobs' => ['last_error' => 'text'],
        'ai_source_mutes' => ['reason_json' => 'json'],
        'ai_suggestions' => ['input_hash' => 'keep', 'model' => 'keep', 'payload_json' => 'json', 'prompt_version' => 'keep', 'provider' => 'keep', 'reasoning' => 'text'],
        'app_meta' => ['k' => 'keep', 'v' => 'keep'],
        'asset_improvements' => ['description' => 'text'],
        'assets' => ['accumulated_account_code' => 'keep', 'acquisition_account_code' => 'keep', 'asset_account_code' => 'keep', 'depreciator_note' => 'text', 'description' => 'text', 'inventory_number' => 'keep', 'name' => 'text', 'summary_account_code' => 'keep'],
        'attachment_checks' => ['ack_fingerprint' => 'keep', 'ack_reason' => 'text', 'entity_type' => 'keep', 'findings' => 'json', 'fingerprint' => 'keep', 'sha256' => 'keep'],
        'auto_posting_policy' => ['operation_type' => 'keep'],
        'automation_recommendation_items' => ['payload' => 'json', 'recommendation_id' => 'keep', 'recommendation_type' => 'keep'],
        'backup_schedule_contract' => ['cron_expr' => 'keep', 'script' => 'keep'],
        'bank_api_months' => ['account_key' => 'bank_account', 'currency' => 'keep'],
        'bank_connections' => ['last_sync_error_code' => 'keep', 'provider' => 'keep', 'token_ciphertext' => 'wipe', 'verified_account_number' => 'bank_account', 'verified_bank_code' => 'keep', 'verified_currency' => 'keep'],
        'bank_counterparty_map' => ['counterparty_account' => 'account_key', 'counterparty_bank' => 'keep'],
        'bank_email_account_mappings' => ['provider_code' => 'keep'],
        'bank_email_attachment_ingests' => ['filename' => 'file_name', 'matched_by' => 'keep', 'message_id' => 'text', 'reason' => 'text', 'sender' => 'text', 'sha256' => 'keep', 'subject' => 'text'],
        'bank_email_imap_settings' => ['email_auth_serv_id' => 'keep', 'failure_flag' => 'keep', 'failure_move_folder' => 'keep', 'folder' => 'keep', 'forwarded_from' => 'text', 'host' => 'host', 'last_scan_message' => 'text', 'name' => 'text', 'password_enc' => 'wipe', 'success_flag' => 'keep', 'success_move_folder' => 'keep', 'username' => 'login'],
        'bank_email_notice_providers' => ['body_pattern' => 'keep', 'code' => 'keep', 'field_patterns' => 'keep', 'name' => 'keep', 'normalizer_config' => 'keep', 'parser_type' => 'keep', 'sender_whitelist' => 'keep', 'subject_pattern' => 'keep'],
        'bank_email_processed_messages' => ['error_message' => 'text', 'fallback_hash' => 'keep', 'message_id' => 'text', 'parsed_payload' => 'json', 'provider_code' => 'keep', 'sender' => 'text', 'subject' => 'text'],
        'bank_match_audit' => ['invoice_ids' => 'keep', 'signals_json' => 'json'],
        'bank_match_suggestions' => ['candidates_json' => 'json', 'reason' => 'keep'],
        'bank_oauth_clients' => ['credentials_ciphertext' => 'wipe', 'provider' => 'keep'],
        'bank_payment_order_submissions' => ['error_code' => 'keep', 'payload_hash' => 'keep', 'provider' => 'keep', 'provider_reference' => 'keep'],
        'bank_posting_rules' => ['applies_currency' => 'keep', 'counterparty_account' => 'bank_account', 'counterparty_bank' => 'keep', 'counterparty_prefix' => 'keep', 'credit_account_code' => 'keep', 'debit_account_code' => 'keep', 'description' => 'text', 'message_contains' => 'text', 'name' => 'text', 'operation_type' => 'keep', 'system_template_key' => 'keep', 'variable_symbol' => 'symbol'],
        'bank_posting_suggestions' => ['ai_model' => 'keep', 'ai_prompt_version' => 'keep', 'ai_provider' => 'keep', 'ai_reasoning' => 'text', 'batch_id' => 'keep', 'credit_account_code' => 'keep', 'debit_account_code' => 'keep', 'description' => 'text', 'detector' => 'keep', 'note' => 'text', 'operation_type' => 'keep', 'snooze_reason' => 'keep'],
        'bank_rule_template_defaults' => ['counterparty_bank' => 'keep', 'counterparty_prefix' => 'keep', 'message_contains' => 'keep', 'name_cs' => 'keep', 'name_en' => 'keep', 'operation_type' => 'keep', 'rule_key' => 'keep', 'template_key' => 'keep', 'vs_placeholder' => 'keep'],
        'bank_rule_templates' => ['counterparty_bank' => 'keep', 'counterparty_prefix' => 'keep', 'message_contains' => 'keep', 'name_cs' => 'keep', 'name_en' => 'keep', 'operation_type' => 'keep', 'rule_key' => 'keep', 'template_key' => 'keep', 'vs_placeholder' => 'keep'],
        'bank_statements' => ['account_number' => 'bank_account', 'bank_code' => 'keep', 'currency' => 'keep', 'file_content' => 'blob_text', 'file_hash' => 'keep', 'file_name' => 'file_name', 'pdf_content' => 'blob_pdf', 'pdf_hash' => 'keep', 'pdf_name' => 'file_name', 'source_ref' => 'text', 'statement_number' => 'keep'],
        'bank_notice_ignore_transfers' => ['ignore_note' => 'text'],
        'bank_transaction_imports' => ['import_fingerprint' => 'keep'],
        'bank_transactions' => ['bank_ref' => 'keep', 'card_last4' => 'card_last4', 'constant_symbol' => 'keep', 'counterparty_account' => 'bank_account', 'counterparty_bank' => 'keep', 'counterparty_name' => 'party_name', 'currency' => 'keep', 'description' => 'text', 'ignore_note' => 'text', 'ignore_origin' => 'keep', 'import_fingerprint' => 'keep', 'match_reason' => 'keep', 'portable_fingerprint' => 'keep', 'processing_error' => 'text', 'source_ref' => 'text', 'specific_symbol' => 'symbol', 'variable_symbol' => 'symbol'],
        'bank_transfer_matches' => ['currency' => 'keep'],
        'branding_profiles' => ['accent_color' => 'keep', 'display_name' => 'party_name', 'email' => 'email', 'email_footer' => 'text', 'logo_path' => 'file_path', 'name' => 'text', 'phone' => 'phone', 'reply_to' => 'email', 'tagline' => 'text', 'web' => 'web'],
        'card_clearing_settings' => ['clearing_synthetic' => 'keep'],
        'cars' => ['brand' => 'keep', 'model' => 'keep', 'name' => 'text', 'note' => 'text', 'registration' => 'shape', 'vin' => 'shape'],
        'cash_document_vat_lines' => ['vat_classification_code' => 'keep'],
        'cash_documents' => ['counter_account_code' => 'keep', 'currency_code' => 'keep', 'description' => 'text', 'doc_number' => 'keep', 'external_barcode' => 'keep', 'partner_dic' => 'dic', 'partner_ic' => 'ico', 'partner_name' => 'party_name', 'rule_key' => 'keep'],
        'cash_registers' => ['account_code' => 'keep', 'currency_code' => 'keep', 'name' => 'text'],
        'catalog_import_profiles' => ['config_json' => 'json', 'name' => 'text'],
        'catalog_import_sources' => ['original_name' => 'file_name', 'sha256' => 'keep', 'storage_key' => 'keep'],
        'catalog_job_items' => ['after_json' => 'json', 'before_json' => 'json', 'error_code' => 'keep', 'input_json' => 'json'],
        'catalog_job_lanes' => ['kind' => 'keep'],
        'catalog_jobs' => ['error_code' => 'keep', 'input_json' => 'json', 'kind' => 'keep', 'lease_token' => 'keep', 'report_json' => 'json'],
        'chart_of_accounts' => ['account_code' => 'keep', 'name' => 'text'],
        'client_bank_accounts' => ['account_key' => 'account_key', 'account_number' => 'bank_account', 'bank_code' => 'keep', 'bank_key' => 'keep', 'iban' => 'iban'],
        'client_email_contacts' => ['contact_name' => 'person_name', 'email' => 'email', 'label' => 'text', 'usages' => 'keep'],
        'clients' => ['city' => 'city', 'company_name' => 'party_name', 'credit_note_number_format' => 'keep', 'dic' => 'dic', 'first_name' => 'first_name', 'ic' => 'ico', 'invoice_number_format' => 'keep', 'last_name' => 'last_name', 'main_email' => 'email', 'note' => 'text', 'phone' => 'phone', 'proforma_number_format' => 'keep', 'related_party_note' => 'text', 'street' => 'street', 'tax_number' => 'shape', 'zip' => 'zip'],
        'cnb_repo_rates' => ['note' => 'keep'],
        'cost_centers' => ['code' => 'keep', 'name' => 'text'],
        'countries' => ['iso2' => 'keep', 'iso3' => 'keep', 'name_cs' => 'keep', 'name_en' => 'keep'],
        'credit_card_accounts' => ['account_number' => 'bank_account', 'analytic_suffix' => 'keep', 'bank_code' => 'keep', 'clearing_suffix' => 'keep', 'currency' => 'keep', 'label' => 'text', 'note' => 'text', 'repayment_account' => 'bank_account', 'repayment_bank_code' => 'keep', 'repayment_vs' => 'symbol'],
        'crm_action_item_dismissals' => ['baseline_ids' => 'keep', 'item_type' => 'keep'],
        'crm_monthly_summary' => ['currency' => 'keep', 'period_ym' => 'keep'],
        'cron_dispatch_claims' => ['script' => 'keep'],
        'cron_heartbeat' => ['last_host' => 'keep', 'last_message' => 'text', 'last_report' => 'json', 'script' => 'keep'],
        'cron_runs' => ['host' => 'keep', 'message' => 'text', 'report' => 'json', 'script' => 'keep'],
        'currencies' => ['account_number' => 'bank_account', 'bank_code' => 'keep', 'bank_name' => 'keep', 'bic' => 'keep', 'code' => 'keep', 'iban' => 'iban', 'label' => 'keep', 'name_cs' => 'keep', 'name_en' => 'keep', 'symbol' => 'keep'],
        'de_movement_classification' => ['note' => 'text'],
        'de_movement_classification_history' => ['new_tax_bucket' => 'keep', 'previous_tax_bucket' => 'keep'],
        'depreciation_entries' => ['detail' => 'json', 'override_reason' => 'text'],
        'dimension_account_rules' => ['account_mask' => 'keep', 'note' => 'text'],
        'dimension_types' => ['code' => 'keep', 'drives_accounts_mask' => 'keep', 'name' => 'text'],
        'dimension_values' => ['code' => 'keep', 'name' => 'text', 'note' => 'text', 'responsible_note' => 'text'],
        'document_dms_messages' => ['annotation' => 'text', 'dm_id' => 'keep', 'dm_status' => 'keep', 'dm_type' => 'keep', 'envelope_xml' => 'text', 'recipient_address' => 'address', 'recipient_box_id' => 'data_box', 'recipient_ident' => 'shape', 'recipient_name' => 'party_name', 'recipient_ref_number' => 'keep', 'sender_address' => 'address', 'sender_box_id' => 'data_box', 'sender_ident' => 'shape', 'sender_name' => 'party_name', 'sender_ref_number' => 'keep', 'sender_type' => 'keep'],
        'document_extractions' => ['barcode' => 'keep', 'buyer_dic' => 'dic', 'buyer_ico' => 'ico', 'buyer_name' => 'party_name', 'card_last4' => 'card_last4', 'currency' => 'keep', 'document_kind' => 'keep', 'document_number' => 'keep', 'error' => 'text', 'license_plate' => 'shape', 'model' => 'keep', 'payload' => 'json', 'provider' => 'keep', 'sha256' => 'keep', 'variable_symbol' => 'symbol', 'vendor_dic' => 'dic', 'vendor_ico' => 'ico', 'vendor_name' => 'party_name'],
        'document_files' => ['filename' => 'file_path', 'mime_type' => 'keep', 'original_name' => 'file_name', 'sha256' => 'keep'],
        'document_folders' => ['name' => 'text'],
        'document_requests' => ['description' => 'text'],
        'document_tags' => ['name' => 'text'],
        'documents' => ['content_text' => 'wipe', 'description' => 'text', 'filename' => 'file_path', 'mime_type' => 'keep', 'original_name' => 'file_name', 'sha256' => 'keep', 'thumb_path' => 'file_path', 'title' => 'text'],
        'ecb_exchange_rates' => ['currency_code' => 'keep'],
        'email_profiles' => ['code' => 'keep', 'dkim_domain' => 'host', 'dkim_selector' => 'keep', 'from_email' => 'email', 'from_name' => 'party_name', 'imap_folder' => 'keep', 'imap_host' => 'host', 'imap_password_enc' => 'wipe', 'imap_username' => 'login', 'name' => 'text', 'reply_to_email' => 'email', 'reply_to_name' => 'party_name', 'sendmail_command' => 'keep', 'smtp_host' => 'host', 'smtp_password_enc' => 'wipe', 'smtp_username' => 'login'],
        'email_templates' => ['body_html' => 'text', 'body_text' => 'text', 'code' => 'keep', 'locale' => 'keep', 'subject' => 'text'],
        'epo_signing_credentials' => ['fingerprint_sha256' => 'keep', 'issuer_dn' => 'keep', 'label' => 'text', 'passphrase_ciphertext' => 'wipe', 'pfx_ciphertext' => 'wipe', 'serial_hex' => 'keep', 'subject_dn' => 'text'],
        'exchange_rates' => ['currency_code' => 'keep'],
        'expense_categories' => ['code' => 'keep', 'label' => 'keep'],
        'expense_classification_rules' => ['description_contains' => 'text', 'name' => 'text', 'target_account_code' => 'keep', 'vendor_name_contains' => 'text'],
        'expense_keyword_catalog' => ['concept_key' => 'keep', 'locale' => 'keep', 'phrase' => 'keep', 'target_account_code' => 'keep'],
        'external_bank_account_mappings' => ['account_number' => 'bank_account', 'external_account_id' => 'keep', 'external_bank_id' => 'keep', 'external_currency_id' => 'keep', 'iban' => 'iban', 'name' => 'text', 'provider' => 'keep'],
        'external_entity_map' => ['entity_type' => 'keep', 'external_id' => 'text', 'external_parent_id' => 'text', 'internal_sub_id' => 'text', 'source_key' => 'text'],
        'fuelings' => ['card_last4' => 'card_last4', 'currency' => 'keep', 'dedup_hash' => 'keep', 'fuel_type' => 'keep', 'note' => 'text', 'raw_text' => 'text', 'receipt_number' => 'keep', 'station' => 'text', 'unit' => 'keep'],
        'fulfillment_return_items' => ['component_snapshot' => 'json'],
        'fulfillment_returns' => ['note' => 'text'],
        'fulfillment_scan_operations' => ['client_operation_id' => 'keep', 'payload_hash' => 'keep', 'payload_json' => 'json', 'result_json' => 'json'],
        'fulfillment_shipment_items' => ['tracking_snapshot' => 'json'],
        'fulfillment_shipments' => ['carrier' => 'keep', 'tracking_number' => 'keep'],
        'fulfillment_task_lines' => ['component_snapshot' => 'json', 'source_line_id' => 'keep'],
        'fulfillment_tasks' => ['source_id' => 'keep', 'source_snapshot' => 'json', 'source_type' => 'keep'],
        'gopay_clearings' => ['account_name' => 'party_name', 'clearing_id' => 'keep', 'currency' => 'keep', 'file_content' => 'blob_text', 'file_hash' => 'keep', 'file_name' => 'file_name', 'payout_issue_code' => 'keep', 'payout_issue_message' => 'text', 'pdf_content' => 'blob_pdf', 'pdf_hash' => 'keep', 'pdf_name' => 'file_name', 'variable_symbol' => 'symbol'],
        'gopay_movements' => ['account_movement_id' => 'keep', 'counterparty_name' => 'party_name', 'currency' => 'keep', 'external_id' => 'keep', 'issue_code' => 'keep', 'issue_message' => 'text', 'order_id' => 'keep', 'payment_channel' => 'keep', 'payment_session_id' => 'keep'],
        'gopay_settings' => ['currency' => 'keep', 'payout_account_number' => 'keep', 'payout_bank_code' => 'keep'],
        'import_jobs' => ['current_step' => 'keep', 'last_error' => 'text', 'log_text' => 'text', 'params' => 'json', 'result_mime' => 'keep', 'result_name' => 'file_name', 'result_path' => 'file_path'],
        'income_tax_finalization_overrides' => ['check_key' => 'keep', 'reason' => 'text'],
        'income_tax_return_snapshots' => ['business_errors' => 'json', 'snapshot_json' => 'json', 'source_manifest' => 'json', 'source_sha256' => 'keep', 'xml_content' => 'text', 'xml_sha256' => 'keep'],
        'income_tax_returns' => ['computed' => 'json', 'inputs' => 'json'],
        'instance_storage_usage' => ['breakdown' => 'keep'],
        'integration_change_log' => ['entity_type' => 'keep'],
        'integration_connections' => ['connection_uuid' => 'keep', 'connector_key' => 'keep', 'credentials_enc' => 'wipe', 'field_ownership_json' => 'keep', 'last_error_code' => 'keep', 'mappings_json' => 'json', 'name' => 'text', 'webhook_secret_enc' => 'wipe', 'webhook_secret_hash' => 'wipe'],
        'integration_inbox' => ['entity_id' => 'keep', 'entity_type' => 'keep', 'event_type' => 'keep', 'external_event_id' => 'keep', 'last_error_code' => 'keep', 'payload_json' => 'json', 'payload_sha256' => 'keep'],
        'integration_inbox_state' => ['entity_id' => 'keep', 'entity_type' => 'keep'],
        'integration_outbox' => ['entity_id' => 'keep', 'entity_type' => 'keep', 'event_type' => 'keep', 'event_uuid' => 'keep', 'idempotency_key' => 'keep', 'last_error_code' => 'keep', 'lease_token' => 'keep', 'payload_json' => 'json', 'payload_sha256' => 'keep'],
        'invoice_attachments' => ['filename' => 'file_path', 'mime_type' => 'keep', 'original_name' => 'file_name', 'sha256' => 'keep'],
        'invoice_counters' => ['period' => 'keep'],
        'invoice_items' => ['description' => 'text', 'oss_consumer_country' => 'keep', 'oss_original_period' => 'keep', 'oss_rate_type' => 'keep', 'revenue_account_code' => 'keep', 'unit' => 'keep', 'vat_classification_code' => 'keep'],
        'invoice_payment_schedule' => ['note' => 'text'],
        'invoice_payments' => ['bank_reference' => 'keep', 'currency' => 'keep', 'note' => 'text', 'variable_symbol' => 'symbol'],
        'invoice_pdfs' => ['filename' => 'file_path', 'reason' => 'keep', 'sent_to' => 'json', 'sha256' => 'keep'],
        'invoice_settlements' => ['note' => 'text'],
        'invoices' => ['approval_decided_by_email' => 'email', 'approval_receipt_hash' => 'keep', 'approval_rejection_reason' => 'text', 'approval_token' => 'token', 'bank_snapshot' => 'json', 'client_snapshot' => 'json', 'import_batch_id' => 'keep', 'imported_pdf_hash' => 'keep', 'imported_pdf_original_name' => 'file_name', 'imported_pdf_path' => 'file_path', 'income_tax_exempt_reason' => 'text', 'note_above_items' => 'text', 'note_below_items' => 'text', 'payment_thanks_sent_to' => 'text', 'payment_variable_symbol' => 'symbol', 'pdf_path' => 'file_path', 'public_token' => 'token', 'revenue_category' => 'keep', 'revenue_rule_key' => 'keep', 'supplier_order_number' => 'keep', 'supplier_snapshot' => 'json', 'varsymbol' => 'symbol', 'vat_classification_code' => 'keep'],
        'isds_gateway_registrations' => ['ats_id' => 'keep', 'certificate_ciphertext' => 'wipe', 'certificate_fingerprint' => 'keep', 'certificate_passphrase_ciphertext' => 'wipe', 'error_url' => 'keep', 'label' => 'text', 'portal_host' => 'keep', 'return_url' => 'keep', 'service_host' => 'keep'],
        'journal_entries' => ['description' => 'text', 'document_no' => 'keep'],
        'journal_entry_attachments' => ['description' => 'text', 'filename' => 'file_path', 'mime_type' => 'keep', 'original_name' => 'file_name', 'sha256' => 'keep'],
        'journal_entry_document_links' => ['note' => 'text'],
        'journal_entry_lines' => ['cost_center' => 'keep', 'currency_code' => 'keep'],
        'journal_entry_notes' => ['body' => 'text'],
        'journal_entry_template_lines' => ['account_code' => 'keep', 'cost_center' => 'keep', 'label' => 'text'],
        'journal_line_pairings' => ['note' => 'text'],
        'journal_entry_templates' => ['description' => 'text', 'name' => 'text', 'seed_key' => 'keep'],
        'journal_integrity_findings' => ['detail' => 'json'],
        'logbook_fuel_scans' => ['parser' => 'keep'],
        'mail_send_log' => ['email_profile' => 'keep', 'template' => 'keep'],
        'manufacturers' => ['code' => 'keep', 'name' => 'keep', 'website' => 'keep'],
        'migration_batch_items' => ['agenda_ico' => 'ico', 'agenda_name' => 'party_name', 'error' => 'text', 'file_name' => 'file_name', 'source' => 'keep', 'summary' => 'json', 'token' => 'keep'],
        'migration_parallel_checks' => ['classifications' => 'json', 'inputs' => 'json', 'note' => 'text', 'period_month' => 'keep', 'result' => 'json', 'source_system' => 'keep'],
        'migrations' => ['filename' => 'keep'],
        'money_s3_import_map' => ['kind' => 'keep', 'money_key' => 'text'],
        'money_s3_imports' => ['agenda_ico' => 'ico', 'agenda_name' => 'party_name', 'automation_snapshot' => 'json', 'backup_sha256' => 'keep', 'money_version' => 'keep', 'protocol' => 'json'],
        'monthly_report_sends' => ['cc' => 'json', 'comment' => 'text', 'sent_to' => 'json', 'smtp_response' => 'text'],
        'offset_agreements' => ['document_no' => 'keep', 'note' => 'text'],
        'other_items' => ['account_code' => 'keep', 'counter_account_code' => 'keep', 'currency' => 'keep', 'document_no' => 'keep', 'kind' => 'keep', 'note' => 'text', 'partner_name' => 'party_name', 'title' => 'text', 'variable_symbol' => 'symbol'],
        'other_item_posting_lines' => ['account_code' => 'keep'],
        'other_item_schedules' => ['template_json' => 'json'],
        'oss_filing_evidence' => ['adjusted_period' => 'keep', 'completeness_json' => 'json', 'consumption_country' => 'keep', 'customer_name' => 'party_name', 'invoice_snapshot_json' => 'json', 'payments_json' => 'json', 'place_evidence_json' => 'json', 'return_currency' => 'keep', 'supply_description' => 'text', 'supply_unit' => 'keep', 'taxable_currency' => 'keep', 'vat_rate_type' => 'keep'],
        'oss_member_state_rates' => ['country' => 'keep', 'note' => 'keep'],
        'payment_cards' => ['analytic_suffix' => 'keep', 'holder_name' => 'person_name', 'label' => 'text', 'last4' => 'card_last4', 'note' => 'text'],
        'payment_order_items' => ['constant_symbol' => 'keep', 'currency' => 'keep', 'message' => 'text', 'payee_account_number' => 'bank_account', 'payee_bank_code' => 'keep', 'payee_bic' => 'keep', 'payee_iban' => 'iban', 'payee_name' => 'party_name', 'specific_symbol' => 'symbol', 'variable_symbol' => 'symbol'],
        'payment_orders' => ['currency' => 'keep', 'note' => 'text', 'payer_account_label' => 'text', 'payer_account_number' => 'bank_account', 'payer_bank_code' => 'keep', 'payer_bic' => 'keep', 'payer_iban' => 'iban'],
        'payroll_absences' => ['compensation_rate_reason' => 'text', 'note' => 'text', 'timezone_name' => 'keep'],
        'payroll_accident_insurance_rates' => ['institution_code' => 'keep'],
        'payroll_agenda_matrix' => ['agenda_code' => 'keep', 'ruleset_hash' => 'keep', 'ruleset_id' => 'keep'],
        'payroll_annual_document_batch_attempts' => ['error_code' => 'keep', 'error_message' => 'text', 'lease_token' => 'keep'],
        'payroll_annual_document_batch_items' => ['last_error_code' => 'keep', 'last_error_message' => 'text', 'lease_token' => 'keep'],
        'payroll_annual_document_batches' => ['idempotency_key_hash' => 'keep', 'scope_key_hash' => 'keep'],
        'payroll_annual_document_revisions' => ['purpose' => 'keep', 'snapshot_ciphertext' => 'wipe', 'snapshot_hash' => 'keep', 'source_manifest_hash' => 'keep', 'source_manifest_json' => 'json'],
        'payroll_annual_document_sources' => ['person_result_hash' => 'keep'],
        'payroll_annual_settlement_certificates' => ['certificate_reference' => 'text', 'evidence_reference' => 'text', 'note' => 'text', 'payer_name' => 'party_name', 'payer_tax_identification' => 'dic'],
        'payroll_annual_settlement_other_caregivers' => ['family_name' => 'last_name', 'given_name' => 'first_name', 'months_mask' => 'keep'],
        'payroll_annual_settlement_requests' => ['annual_claims_note' => 'text', 'filing_obligation_reason' => 'text', 'note' => 'text', 'request_evidence_reference' => 'text'],
        'payroll_attendance_import_rows' => ['component_code' => 'keep', 'meaning' => 'keep', 'source_ref' => 'text'],
        'payroll_attendance_imports' => ['content_sha256' => 'keep', 'files_json' => 'json', 'rules_json' => 'json', 'source_system' => 'keep'],
        'payroll_average_earning_snapshots' => ['input_hash' => 'keep', 'input_trace' => 'json', 'rationale' => 'text', 'ruleset_hash' => 'keep', 'ruleset_id' => 'keep'],
        'payroll_benefit_accumulators' => ['reversal_reason' => 'text'],
        'payroll_business_trip_items' => ['description' => 'text', 'document_reference' => 'text'],
        'payroll_business_trips' => ['calculation_hash' => 'keep', 'calculation_json' => 'json', 'country_code' => 'keep', 'destination_place' => 'city', 'origin_place' => 'city', 'purpose' => 'text', 'ruleset_id' => 'keep', 'timezone_name' => 'keep'],
        'payroll_calendar_days' => ['holiday_code' => 'keep', 'holiday_name' => 'keep', 'note' => 'text'],
        'payroll_component_definitions' => ['accounting_credit_code' => 'keep', 'accounting_debit_code' => 'keep', 'code' => 'keep', 'name' => 'text'],
        'payroll_component_jmhz_mappings' => ['target_attribute_id' => 'keep'],
        'payroll_data_migration_markers' => ['migration_key' => 'keep'],
        'payroll_deduction_agreement_versions' => ['note' => 'text', 'reason' => 'text', 'recipient_reference' => 'text', 'title' => 'text'],
        'payroll_deduction_agreements' => ['agreement_reference' => 'text', 'note' => 'text', 'recipient_reference' => 'text', 'title' => 'text'],
        'payroll_deduction_ledger' => ['event_key_hash' => 'keep', 'metadata_json' => 'json'],
        'payroll_dependants' => ['birth_number_ciphertext' => 'sealed:personal_identifier:birth_number_hash:birth_number_masked:id', 'birth_number_hash' => 'sealed_companion', 'birth_number_masked' => 'sealed_companion', 'family_name' => 'last_name', 'full_name' => 'person_name', 'given_name' => 'first_name', 'note' => 'text'],
        'payroll_dimensions' => ['code' => 'keep', 'default_account_code' => 'keep', 'name' => 'text'],
        'payroll_discount_intents' => ['rejection_reason' => 'text'],
        'payroll_document_batch_attempts' => ['error_code' => 'keep', 'error_message' => 'text', 'lease_token' => 'keep'],
        'payroll_document_batch_items' => ['last_error_code' => 'keep', 'last_error_message' => 'text', 'lease_token' => 'keep', 'source_snapshot_hash' => 'keep'],
        'payroll_document_batches' => ['idempotency_key_hash' => 'keep', 'source_snapshot_hash' => 'keep'],
        'payroll_document_data_keys' => ['destroy_reason' => 'text', 'key_algorithm' => 'keep', 'wrapped_key' => 'wipe'],
        'payroll_eldp_manual_completions' => ['authority_reference' => 'text', 'confirmation_mime_type' => 'keep', 'confirmation_sha256' => 'keep', 'evidence_manifest_json' => 'json', 'evidence_sha256' => 'keep', 'idempotency_key_hash' => 'keep', 'request_fingerprint' => 'keep'],
        'payroll_eldp_statement_claims' => ['confirmation_fingerprint' => 'keep', 'idempotency_key_hash' => 'keep'],
        'payroll_eldp_statement_sources' => ['input_snapshot_hash' => 'keep', 'result_snapshot_hash' => 'keep'],
        'payroll_eldp_statements' => ['builder_version' => 'keep', 'deadline_ruleset_hash' => 'keep', 'deadline_ruleset_id' => 'keep', 'idempotency_key_hash' => 'keep', 'request_fingerprint' => 'keep', 'schema_reference' => 'keep', 'source_manifest_json' => 'json', 'source_manifest_sha256' => 'keep', 'statement_ciphertext' => 'wipe', 'statement_fingerprint' => 'keep', 'xml_sha256' => 'keep', 'xsd_bundle_sha256' => 'keep', 'xsd_package_key' => 'keep'],
        'payroll_employee_profiles' => ['partner_settlement_account_code' => 'keep'],
        'payroll_employees' => ['address' => 'address', 'birth_number' => 'birth_number', 'full_name' => 'person_name', 'net_settlement_account_code' => 'keep', 'taxpayer_type' => 'keep'],
        'payroll_employer_policies' => ['balance_rounding_mode' => 'keep', 'delivery_channel' => 'keep', 'home_office_policy' => 'keep', 'payday_business_day_rule' => 'keep', 'source_kind' => 'keep', 'source_reference' => 'text', 'travel_expense_policy' => 'keep'],
        'payroll_employer_policy_audit' => ['action' => 'keep', 'snapshot_hash' => 'keep', 'snapshot_json' => 'json'],
        'payroll_employer_settings' => ['accident_insurance_credit_account' => 'keep', 'accident_insurance_debit_account' => 'keep', 'default_health_insurer_code' => 'keep', 'employee_receivable_debit_account' => 'keep', 'employer_insurance_debit_account' => 'keep', 'employer_registration_number' => 'shape', 'employment_gross_credit_account' => 'keep', 'employment_gross_debit_account' => 'keep', 'enforcement_deductions_credit_account' => 'keep', 'enforcement_fee_revenue_credit_account' => 'keep', 'health_insurance_credit_account' => 'keep', 'income_tax_credit_account' => 'keep', 'non_deductible_benefit_debit_account' => 'keep', 'other_deductions_credit_account' => 'keep', 'partner_gross_credit_account' => 'keep', 'partner_gross_debit_account' => 'keep', 'partner_settlement_credit_account' => 'keep', 'payroll_contact_email' => 'email', 'payroll_contact_name' => 'person_name', 'payroll_contact_phone' => 'phone', 'risky_savings_credit_account' => 'keep', 'risky_savings_debit_account' => 'keep', 'social_insurance_credit_account' => 'keep', 'social_security_office_code' => 'keep', 'statutory_gross_credit_account' => 'keep', 'statutory_gross_debit_account' => 'keep', 'travel_expense_debit_account' => 'keep', 'withholding_tax_credit_account' => 'keep'],
        'payroll_employment_checklist_items' => ['deadline_ruleset_id' => 'keep', 'deadline_source' => 'keep', 'deadline_source_status' => 'keep', 'item_key' => 'keep', 'note' => 'text'],
        'payroll_employment_events' => ['diff_json' => 'json', 'from_status' => 'keep', 'note' => 'text', 'to_status' => 'keep'],
        'payroll_employment_exit_revisions' => ['purpose' => 'keep', 'snapshot_ciphertext' => 'wipe', 'snapshot_hash' => 'keep', 'source_manifest_hash' => 'keep', 'source_manifest_json' => 'json'],
        'payroll_employment_external_ids' => ['source_reference_hash' => 'keep', 'value_ciphertext' => 'sealed:employment_external_identifier:value_hash:value_masked:id', 'value_hash' => 'sealed_companion', 'value_masked' => 'sealed_companion'],
        'payroll_employment_surcharge_policies' => ['agreement_reference' => 'text', 'note' => 'text'],
        'payroll_employment_survivors' => ['bank_account' => 'bank_account', 'full_name' => 'person_name', 'note' => 'text'],
        'payroll_employment_terminations' => ['death_tax_assessment' => 'text', 'employee_stated_reason' => 'text', 'severance_override_reason' => 'text'],
        'payroll_employment_deferred_incomes' => ['note' => 'text'],
        'payroll_employment_terms' => ['activity_code' => 'keep', 'change_reason' => 'text', 'cz_isco_code' => 'keep', 'foreign_legislation_country_code' => 'keep', 'jmhz_apz_instrument_code' => 'keep', 'jmhz_assignment_user_country_code' => 'keep', 'jmhz_assignment_user_foreign_id' => 'shape', 'jmhz_assignment_user_ico' => 'ico', 'jmhz_assignment_user_name' => 'party_name', 'jmhz_external_codebook_manifest_sha256' => 'keep', 'jmhz_external_codebook_overlay_key' => 'keep', 'jmhz_relationship_detail_code' => 'keep', 'jmhz_workplace_country_code' => 'keep', 'jmhz_workplace_municipality_code' => 'keep', 'probable_earning_rationale' => 'text', 'regular_workplace' => 'address', 'social_employer_rate_category_evidence' => 'text', 'social_part_time_discount_evidence' => 'text', 'work_place' => 'address'],
        'payroll_employments' => ['code' => 'keep'],
        'payroll_enforcement_allocations' => ['allocation_key' => 'keep'],
        'payroll_enforcement_case_documents' => ['document_sha256' => 'keep'],
        'payroll_enforcement_case_parties' => ['party_name' => 'party_name', 'party_reference' => 'text', 'source_document_sha256' => 'keep'],
        'payroll_enforcement_cases' => ['case_key' => 'keep'],
        'payroll_enforcement_claim_breakdowns' => ['change_reason' => 'text', 'source_document_sha256' => 'keep'],
        'payroll_enforcement_claims' => ['claim_key' => 'keep', 'enforcement_order_key' => 'keep'],
        'payroll_enforcement_dependants' => ['dependant_key' => 'keep'],
        'payroll_enforcement_events' => ['command_name' => 'keep', 'decision_evidence_hash' => 'keep', 'from_status' => 'keep', 'reason' => 'text', 'to_status' => 'keep'],
        'payroll_enforcement_ledger' => ['idempotency_key_hash' => 'keep'],
        'payroll_enforcement_month_results' => ['idempotency_key_hash' => 'keep', 'input_snapshot_hash' => 'keep', 'input_snapshot_json' => 'json', 'result_snapshot_hash' => 'keep', 'result_snapshot_json' => 'json', 'ruleset_hash' => 'keep', 'ruleset_id' => 'keep'],
        'payroll_enforcement_recipient_instructions' => ['change_reason' => 'text', 'source_document_sha256' => 'keep'],
        'payroll_enforcement_termination_notices' => ['new_payer_name' => 'party_name', 'new_payer_reference' => 'text', 'snapshot_hash' => 'keep', 'snapshot_json' => 'json'],
        'payroll_enforcement_xmlzam_requests' => ['executor_box_id' => 'data_box', 'request_identifier' => 'keep', 'snapshot_ciphertext' => 'wipe', 'snapshot_fingerprint' => 'keep', 'source_xml_sha256' => 'keep'],
        'payroll_enforcement_xmlzam_responses' => ['idempotency_key_hash' => 'keep', 'response_identifier' => 'keep', 'snapshot_ciphertext' => 'wipe', 'snapshot_fingerprint' => 'keep', 'source_manifest_json' => 'json', 'source_manifest_sha256' => 'keep', 'xml_ciphertext' => 'wipe', 'xml_sha256' => 'keep'],
        'payroll_erasure_proposal_items' => ['cascade_counts' => 'keep', 'governing_category' => 'keep', 'governing_source' => 'keep', 'governing_source_status' => 'keep', 'skip_reason' => 'text'],
        'payroll_erasure_proposals' => ['note' => 'text'],
        'payroll_external_jmhz_submission_forms' => ['form_guid' => 'keep', 'form_type' => 'keep', 'payload_ciphertext' => 'sealed:external_jmhz_payload:payload_hash:-:id', 'payload_hash' => 'sealed_companion', 'payload_sha256' => 'keep', 'source_relation_ref' => 'keep'],
        'payroll_external_jmhz_submissions' => ['corrected_source_key' => 'keep', 'file_name' => 'file_name', 'note' => 'text', 'payload_ciphertext' => 'sealed:external_jmhz_payload:payload_hash:-:id', 'payload_hash' => 'sealed_companion', 'payload_sha256' => 'keep', 'period' => 'keep', 'program' => 'keep', 'source_key' => 'keep', 'submission_guid' => 'keep', 'submission_type' => 'keep'],
        'payroll_generated_documents' => ['document_kind' => 'keep', 'file_sha256' => 'keep', 'idempotency_key_hash' => 'keep', 'manifest_json' => 'json', 'mime_type' => 'keep', 'renderer_version' => 'keep', 'revision_snapshot_hash' => 'keep', 'source_snapshot_hash' => 'keep', 'storage_key' => 'keep', 'suggested_filename' => 'file_name', 'template_version' => 'keep'],
        'payroll_identity_resolution_tasks' => ['reason_code' => 'keep', 'resolution_evidence_hash' => 'keep'],
        'payroll_import_links' => ['external_key' => 'text', 'source_system' => 'keep'],
        'payroll_import_profiles' => ['components_json' => 'json', 'name' => 'text', 'rules_json' => 'json', 'sample_rules_sha256' => 'keep', 'source_system' => 'keep'],
        'payroll_imported_jmhz_protocols' => ['correlation_reference' => 'keep', 'dedupe_key' => 'keep', 'payload_sha256' => 'keep', 'payload_xml' => 'text', 'protocol_dated_at' => 'keep', 'source_filename' => 'file_name', 'status_name' => 'keep', 'submission_guid' => 'keep', 'submitted_at' => 'keep', 'variable_symbol' => 'symbol'],
        'payroll_input_import_rows' => ['errors_json' => 'json', 'external_id' => 'text', 'normalized_payload' => 'json'],
        'payroll_input_imports' => ['content_hash' => 'keep', 'source_name' => 'file_name'],
        'payroll_inputs' => ['benefit_allocation_json' => 'json', 'component_snapshot_hash' => 'keep', 'component_snapshot_json' => 'json', 'external_id' => 'text', 'source_snapshot_hash' => 'keep', 'source_snapshot_json' => 'json'],
        'payroll_insolvency_payment_instructions' => ['decision_document_hash' => 'keep', 'institution_account_hash' => 'keep', 'institution_code' => 'keep', 'institution_type' => 'keep', 'instruction_hash' => 'keep'],
        'payroll_institution_accounts' => ['bank_account_ciphertext' => 'keep', 'bank_account_hash' => 'keep', 'bank_account_masked' => 'keep', 'constant_symbol' => 'keep', 'currency_code' => 'keep', 'institution_name' => 'keep', 'source_kind' => 'keep', 'source_reference' => 'text', 'specific_symbol' => 'symbol', 'variable_symbol' => 'symbol'],
        'payroll_institutions' => ['institution_code' => 'keep', 'institution_type' => 'keep'],
        'payroll_jmhz_codebook_entries' => ['item_code' => 'keep', 'label' => 'keep', 'metadata_json' => 'keep', 'parent_code' => 'keep', 'row_hash' => 'keep'],
        'payroll_jmhz_codebooks' => ['codebook_key' => 'keep', 'content_hash' => 'keep', 'source_kind' => 'keep', 'source_metadata_json' => 'keep', 'source_name' => 'keep', 'source_url' => 'keep'],
        'payroll_jmhz_control_attribute_refs' => ['attribute_id' => 'keep', 'row_hash' => 'keep'],
        'payroll_jmhz_control_catalogs' => ['catalog_key' => 'keep', 'manifest_json' => 'keep', 'manifest_sha256' => 'keep', 'source_filename' => 'keep', 'source_sha256' => 'keep', 'version' => 'keep'],
        'payroll_jmhz_control_definitions' => ['area' => 'keep', 'attribute_refs_raw' => 'keep', 'category' => 'keep', 'detail_formula' => 'keep', 'detail_text' => 'keep', 'error_message' => 'keep', 'error_message_formula' => 'keep', 'name' => 'keep', 'note' => 'keep', 'owner_name' => 'keep', 'portal_passability' => 'keep', 'portal_system' => 'keep', 'rejection_scope' => 'keep', 'remote_passability' => 'keep', 'remote_system' => 'keep', 'row_hash' => 'keep', 'source_label' => 'keep', 'symbolic_refs_json' => 'keep'],
        'payroll_jmhz_control_parameter_refs' => ['resolution' => 'keep', 'row_hash' => 'keep'],
        'payroll_jmhz_control_parameter_values' => ['canonical_value' => 'keep', 'normalized_value' => 'keep', 'raw_type' => 'keep', 'raw_value' => 'keep', 'row_hash' => 'keep', 'source_cell' => 'keep'],
        'payroll_jmhz_control_parameters' => ['control_refs_anomaly' => 'keep', 'control_refs_formatted' => 'keep', 'control_refs_raw' => 'keep', 'name' => 'keep', 'parameter_key' => 'keep', 'row_hash' => 'keep'],
        'payroll_jmhz_deferrals' => ['blocker_codes_json' => 'json', 'decided_snapshot_fingerprint' => 'keep', 'reason' => 'text', 'revoke_reason' => 'text'],
        'payroll_jmhz_dictionary_attributes' => ['area' => 'keep', 'attribute_id' => 'keep', 'cardinality' => 'keep', 'class_name' => 'keep', 'codebook_key' => 'keep', 'data_type' => 'keep', 'data_type_refinement' => 'keep', 'employee_registration_marker' => 'keep', 'employer_registration_marker' => 'keep', 'monthly_marker' => 'keep', 'name' => 'keep', 'regzec_xsd_mapping' => 'keep', 'row_hash' => 'keep', 'subclass_name' => 'keep', 'xsd_mapping' => 'keep'],
        'payroll_jmhz_eldp_evidence_snapshots' => ['idempotency_key_hash' => 'keep', 'request_fingerprint' => 'keep', 'schema_reference' => 'keep', 'snapshot_ciphertext' => 'wipe', 'snapshot_fingerprint' => 'keep', 'source_manifest_json' => 'json', 'source_manifest_sha256' => 'keep'],
        'payroll_jmhz_eldp_idempotency_claims' => ['confirmation_fingerprint' => 'keep', 'idempotency_key_hash' => 'keep'],
        'payroll_jmhz_employer_annual_evidence' => ['collective_agreement_types_json' => 'keep', 'evidence_reference' => 'text', 'ownership_form' => 'keep', 'payload_sha256' => 'keep', 'schema_reference' => 'keep', 'spec_manifest_sha256' => 'keep'],
        'payroll_jmhz_field_requirements' => ['attribute_id' => 'keep', 'condition_note_raw' => 'keep', 'effect_kind' => 'keep', 'effect_raw' => 'keep', 'requirement_kind' => 'keep', 'requirement_raw' => 'keep', 'row_hash' => 'keep', 'source_cell' => 'keep', 'translation_raw' => 'keep'],
        'payroll_jmhz_interaction_attribute_refs' => ['attribute_id' => 'keep', 'row_hash' => 'keep', 'source_cell' => 'keep', 'source_match_raw' => 'keep'],
        'payroll_jmhz_interaction_definitions' => ['condition_raw' => 'keep', 'interaction_id_raw' => 'keep', 'interaction_key' => 'keep', 'note_raw' => 'keep', 'portal_text' => 'keep', 'row_hash' => 'keep', 'source_sheet' => 'keep', 'trigger_kind' => 'keep'],
        'payroll_jmhz_master_attribute_axis' => ['attribute_id' => 'keep', 'row_hash' => 'keep'],
        'payroll_jmhz_matrix_evidence_axes' => ['axis_key' => 'keep', 'axis_kind' => 'keep', 'dictionary_cached_vector_sha256' => 'keep', 'dictionary_formula_vector_sha256' => 'keep', 'expected_effect' => 'keep', 'expected_matrix_key' => 'keep', 'label_raw' => 'keep', 'raw_vector_sha256' => 'keep', 'reconciliation_status' => 'keep', 'row_hash' => 'keep', 'source_column' => 'keep', 'source_sheet' => 'keep'],
        'payroll_jmhz_matrix_evidence_members' => ['attribute_id' => 'keep', 'raw_type' => 'keep', 'raw_value' => 'keep', 'row_hash' => 'keep', 'source_cell' => 'keep'],
        'payroll_jmhz_ordinary_evidence_idempotency_claims' => ['confirmation_fingerprint' => 'keep', 'idempotency_key_hash' => 'keep'],
        'payroll_jmhz_ordinary_evidence_snapshots' => ['idempotency_key_hash' => 'keep', 'request_fingerprint' => 'keep', 'schema_reference' => 'keep', 'snapshot_ciphertext' => 'wipe', 'snapshot_fingerprint' => 'keep', 'source_manifest_json' => 'json', 'source_manifest_sha256' => 'keep'],
        'payroll_jmhz_preparation_idempotency_claims' => ['idempotency_key_hash' => 'keep'],
        'payroll_jmhz_preparation_snapshots' => ['builder_version' => 'keep', 'idempotency_key_hash' => 'keep', 'readiness_json' => 'json', 'readiness_sha256' => 'keep', 'request_fingerprint' => 'keep', 'scenario_key' => 'keep', 'scenario_set_json' => 'json', 'snapshot_ciphertext' => 'wipe', 'snapshot_fingerprint' => 'keep', 'source_manifest_json' => 'json', 'source_manifest_sha256' => 'keep'],
        'payroll_jmhz_protocol_form_outcomes' => ['errors_ciphertext' => 'wipe', 'errors_sha256' => 'keep', 'external_employment_reference' => 'text', 'external_person_reference' => 'text', 'form_guid' => 'keep', 'protocol_status_name' => 'keep'],
        'payroll_jmhz_requirement_matrices' => ['matrix_hash' => 'keep', 'matrix_key' => 'keep', 'matrix_kind' => 'keep', 'row_hash' => 'keep', 'selector_raw' => 'keep', 'source_sheet' => 'keep'],
        'payroll_jmhz_scenario_catalogs' => ['catalog_key' => 'keep', 'manifest_json' => 'keep', 'manifest_sha256' => 'keep', 'source_filename' => 'keep', 'source_sha256' => 'keep', 'version' => 'keep'],
        'payroll_jmhz_scenario_definitions' => ['business_description_cell_kind' => 'keep', 'business_description_raw' => 'keep', 'condition_raw' => 'keep', 'name_raw' => 'keep', 'row_hash' => 'keep', 'scenario_key' => 'keep', 'selection_kind' => 'keep', 'selector_raw' => 'keep', 'selector_raw_type' => 'keep', 'source_sheet' => 'keep', 'xsd_entrypoint' => 'keep'],
        'payroll_jmhz_spec_packages' => ['control_catalog_version' => 'keep', 'dictionary_version' => 'keep', 'instructions_version' => 'keep', 'manifest_json' => 'keep', 'manifest_sha256' => 'keep', 'package_key' => 'keep', 'process_version' => 'keep', 'schema_version' => 'keep', 'xsd_version' => 'keep'],
        'payroll_jmhz_work_month_revisions' => ['confirmation_note' => 'text', 'control_catalog_key' => 'keep', 'control_manifest_sha256' => 'keep', 'derivation_version' => 'keep', 'provenance_json' => 'json', 'scenario_catalog_key' => 'keep', 'scenario_manifest_sha256' => 'keep', 'source_snapshot_json' => 'json', 'source_snapshot_sha256' => 'keep', 'spec_manifest_sha256' => 'keep', 'summary_sha256' => 'keep'],
        'payroll_leave_entitlement_snapshots' => ['calculation_trace' => 'json', 'input_hash' => 'keep', 'rationale' => 'text', 'source_snapshot_hash' => 'keep'],
        'payroll_leave_ledger' => ['reason' => 'text', 'source_hash' => 'keep'],
        'payroll_migration_reference_totals' => ['activity_code' => 'keep', 'external_person_ref' => 'text', 'external_relationship_ref' => 'text', 'import_reference' => 'text', 'relation_type' => 'keep'],
        'payroll_monthly_records' => ['breakdown' => 'json', 'retired_reason' => 'text'],
        'payroll_net_results' => ['result_hash' => 'keep', 'result_json' => 'json'],
        'payroll_obligations' => ['agenda_code' => 'keep', 'idempotency_key_hash' => 'keep', 'request_fingerprint' => 'keep', 'source_event_hash' => 'keep', 'source_event_reference' => 'text', 'source_event_type' => 'keep', 'subject_reference' => 'text'],
        'payroll_office_registration_versions' => ['social_security_variable_symbol' => 'symbol', 'source_reference' => 'text'],
        'payroll_offices' => ['code' => 'keep', 'name' => 'keep', 'social_security_variable_symbol' => 'symbol', 'test_social_security_variable_symbol' => 'symbol'],
        'payroll_operational_reconciliation_issue_events' => ['source_hash' => 'keep', 'source_snapshot_json' => 'json'],
        'payroll_operational_reconciliation_issues' => ['category' => 'keep', 'issue_key' => 'text', 'source_hash' => 'keep', 'source_snapshot_json' => 'json'],
        'payroll_overtime_averaging_periods' => ['basis' => 'keep', 'collective_agreement_reference' => 'text', 'note' => 'text'],
        'payroll_overtime_compensations' => ['document_reference' => 'text', 'note' => 'text'],
        'payroll_overtime_consents' => ['document_reference' => 'text', 'note' => 'text'],
        'payroll_overtime_protections' => ['document_reference' => 'text', 'note' => 'text', 'protection' => 'keep'],
        'payroll_payment_allocations' => ['idempotency_key_hash' => 'keep'],
        'payroll_payment_batches' => ['batch_reference' => 'text', 'currency_code' => 'keep', 'idempotency_key_hash' => 'keep', 'payer_reference' => 'text', 'snapshot_ciphertext' => 'wipe', 'snapshot_hash' => 'keep'],
        'payroll_payment_export_idempotency_keys' => ['idempotency_key_hash' => 'keep'],
        'payroll_payment_exports' => ['exporter_version' => 'keep', 'file_sha256' => 'keep', 'idempotency_key_hash' => 'keep', 'manifest_json' => 'json', 'mime_type' => 'keep', 'source_snapshot_hash' => 'keep', 'storage_key' => 'keep', 'suggested_filename' => 'file_name'],
        'payroll_payment_items' => ['idempotency_key_hash' => 'keep', 'instruction_ciphertext' => 'wipe', 'instruction_hash' => 'keep', 'item_reference' => 'text', 'recipient_reference' => 'text'],
        'payroll_payment_liabilities' => ['currency_code' => 'keep', 'idempotency_key_hash' => 'keep', 'liability_reference' => 'text', 'recipient_reference' => 'text', 'source_snapshot_hash' => 'keep', 'source_snapshot_json' => 'json'],
        'payroll_payment_match_postings' => ['posting_skipped_reason' => 'keep'],
        'payroll_payment_matches' => ['evidence_currency_code' => 'keep', 'evidence_fact_hash' => 'keep', 'idempotency_key_hash' => 'keep'],
        'payroll_payment_settlement_signals' => ['note' => 'text'],
        'payroll_payout_allocations' => ['allocation_reference' => 'text', 'destination_reference' => 'text'],
        'payroll_payout_rules' => ['allocation_reference' => 'text', 'destination_reference' => 'text'],
        'payroll_period_export_job_attempts' => ['error_code' => 'keep', 'error_message' => 'text', 'lease_token' => 'keep'],
        'payroll_period_export_job_part_attempts' => ['error_code' => 'keep', 'error_message' => 'text', 'lease_token' => 'keep'],
        'payroll_period_export_job_parts' => ['last_error_code' => 'keep', 'last_error_message' => 'text', 'lease_token' => 'keep', 'part_key' => 'keep', 'source_sha256' => 'keep', 'storage_key' => 'keep'],
        'payroll_period_export_jobs' => ['last_error_code' => 'keep', 'last_error_message' => 'text', 'lease_token' => 'keep'],
        'payroll_period_exports' => ['file_sha256' => 'keep', 'manifest_json' => 'json', 'mime_type' => 'keep', 'source_manifest_hash' => 'keep', 'storage_key' => 'keep', 'suggested_filename' => 'file_name'],
        'payroll_period_ownership' => ['source_type' => 'keep'],
        'payroll_person_accounts' => ['bank_account_ciphertext' => 'sealed:bank_account:bank_account_hash:bank_account_masked:id', 'bank_account_hash' => 'sealed_companion', 'bank_account_masked' => 'sealed_companion', 'label' => 'text'],
        'payroll_person_addresses' => ['city' => 'city', 'country_code' => 'keep', 'postal_code' => 'zip', 'street_line' => 'street'],
        'payroll_person_contacts' => ['contact_value_ciphertext' => 'sealed:@contact_type:contact_value_hash:contact_value_masked:id', 'contact_value_hash' => 'sealed_companion', 'contact_value_masked' => 'sealed_companion'],
        'payroll_person_external_ids' => ['source_reference_hash' => 'keep', 'value_ciphertext' => 'sealed:person_external_identifier:value_hash:value_masked:id', 'value_hash' => 'sealed_companion', 'value_masked' => 'sealed_companion'],
        'payroll_person_foreign_permits' => ['document_sha256' => 'keep', 'issuing_country_code' => 'keep', 'permit_label' => 'text'],
        'payroll_person_health_coverage_history' => ['evidence_note' => 'text', 'foreign_country_code' => 'keep', 'health_evidence_document_sha256' => 'keep', 'insurer_code' => 'keep', 'insurer_evidence_reference' => 'text', 'jurisdiction_evidence_reference' => 'text'],
        'payroll_person_health_minimum_reductions' => ['evidence_note' => 'text', 'evidence_reference' => 'text'],
        'payroll_person_health_month_evidence' => ['evidence_note' => 'text', 'selected_top_up_employer_evidence_reference' => 'text', 'selected_top_up_employer_reference' => 'text', 'top_up_responsibility_evidence_reference' => 'text'],
        'payroll_person_health_other_employer_bases' => ['employer_reference' => 'text', 'evidence_note' => 'text', 'evidence_reference' => 'text'],
        'payroll_person_identifiers' => ['value_ciphertext' => 'sealed:@identifier_type:value_hash:value_masked:id', 'value_hash' => 'sealed_companion', 'value_masked' => 'sealed_companion'],
        'payroll_person_identity_history' => ['birth_country_code' => 'keep', 'birth_place' => 'city', 'birth_surname' => 'last_name', 'citizenship_country_code' => 'keep', 'first_name' => 'first_name', 'full_name' => 'person_name', 'last_name' => 'last_name', 'title_prefix' => 'keep', 'title_suffix' => 'keep'],
        'payroll_person_social_discount_claims' => ['evidence_note' => 'text', 'evidence_reference' => 'text'],
        'payroll_person_social_jurisdictions' => ['a1_certificate_reference' => 'text', 'evidence_note' => 'text', 'foreign_country_code' => 'keep', 'jurisdiction_evidence_reference' => 'text'],
        'payroll_person_tax_child_claims' => ['child_reference' => 'text', 'claim_reason' => 'text', 'evidence_note' => 'text', 'evidence_reference' => 'text', 'other_caregiver_family_name' => 'last_name', 'other_caregiver_given_name' => 'first_name'],
        'payroll_person_tax_credit_claims' => ['evidence_note' => 'text', 'evidence_reference' => 'text'],
        'payroll_person_tax_declarations' => ['evidence_note' => 'text', 'evidence_reference' => 'text'],
        'payroll_person_tax_residences' => ['country_code' => 'keep', 'evidence_note' => 'text', 'evidence_reference' => 'text'],
        'payroll_posting_allocations' => ['account_code' => 'keep', 'allocation_key' => 'keep', 'cost_center' => 'keep', 'description' => 'text', 'dimensions' => 'keep'],
        'payroll_posting_batches' => ['delta_hash' => 'keep', 'target_hash' => 'keep'],
        'payroll_posting_map_proposals' => ['confirmed_json' => 'json', 'proposal_json' => 'json', 'source_reference' => 'text'],
        'payroll_production_qualification_documents' => ['document_sha256' => 'keep', 'evidence_key' => 'keep'],
        'payroll_production_qualifications' => ['evidence_json' => 'json', 'evidence_sha256' => 'keep', 'support_matrix_sha256' => 'keep', 'support_matrix_version' => 'keep'],
        'payroll_recurring_components' => ['note' => 'text'],
        'payroll_registration_a1_profiles' => ['profile_ciphertext' => 'sealed:registration_a1_profile:profile_hash:-:employment_id', 'profile_hash' => 'sealed_companion', 'reference_hash' => 'keep'],
        'payroll_registration_a2_evidence_ledger' => ['plan_json' => 'json', 'plan_sha256' => 'keep', 'policy_reference' => 'keep', 'schema_reference' => 'keep'],
        'payroll_registration_change_proposals' => ['baseline_fingerprint' => 'keep', 'current_fingerprint' => 'keep', 'deadline_ruleset_id' => 'keep', 'deadline_source' => 'keep', 'duty_kind' => 'keep', 'findings_json' => 'json', 'resolution_note' => 'text'],
        'payroll_registration_change_scans' => ['source_watermark' => 'keep'],
        'payroll_registration_event_snapshots' => ['interaction_code' => 'keep', 'snapshot_ciphertext' => 'wipe', 'snapshot_fingerprint' => 'keep', 'source_kind' => 'keep', 'source_manifest_hash' => 'keep', 'source_manifest_json' => 'json', 'source_reference' => 'text'],
        'payroll_registration_identity_snapshots' => ['idempotency_key_hash' => 'keep', 'request_fingerprint' => 'keep', 'schema_reference' => 'keep', 'snapshot_ciphertext' => 'wipe', 'snapshot_fingerprint' => 'keep', 'source_manifest_hash' => 'keep', 'source_manifest_json' => 'json'],
        'payroll_regzel_employer_profiles' => ['payer_reference_number' => 'shape', 'tax_office_code' => 'keep', 'tax_office_workplace_code' => 'keep'],
        'payroll_regzel_payload_snapshots' => ['idempotency_key_hash' => 'keep', 'mapping_version' => 'keep', 'request_fingerprint' => 'keep', 'snapshot_ciphertext' => 'wipe', 'source_manifest_json' => 'json', 'source_snapshot_hash' => 'keep', 'xml_sha256' => 'keep', 'xsd_version' => 'keep'],
        'payroll_retention_policies' => ['category' => 'keep', 'reason' => 'text'],
        'payroll_risky_savings_contributions' => ['institution_account_hash' => 'keep', 'institution_account_masked' => 'keep', 'payment_message' => 'text', 'payment_reference' => 'text', 'pension_company' => 'keep', 'product_reference' => 'shape', 'specific_symbol' => 'symbol', 'variable_symbol' => 'symbol'],
        'payroll_risky_savings_evidence' => ['evidence_reference' => 'text', 'institution_account_hash' => 'keep', 'institution_account_masked' => 'keep', 'payment_message' => 'text', 'payment_reference' => 'text', 'pension_company' => 'keep', 'product_reference' => 'shape', 'specific_symbol' => 'symbol', 'variable_symbol' => 'symbol'],
        'payroll_ruleset_audit' => ['action' => 'keep', 'domain' => 'keep', 'lifecycle' => 'keep', 'previous_hash' => 'keep', 'reason' => 'text', 'ruleset_id' => 'keep', 'snapshot_hash' => 'keep', 'snapshot_json' => 'keep'],
        'payroll_rulesets' => ['capability' => 'keep', 'content_hash' => 'keep', 'data' => 'keep', 'domain' => 'keep', 'lifecycle' => 'keep', 'reason' => 'text', 'ruleset_id' => 'keep', 'version' => 'keep'],
        'payroll_run_commands' => ['command_name' => 'keep', 'from_status' => 'keep', 'idempotency_key_hash' => 'keep', 'request_hash' => 'keep', 'result_json' => 'json', 'to_status' => 'keep'],
        'payroll_run_employments' => ['input_hash' => 'keep', 'input_json' => 'json', 'result_hash' => 'keep', 'result_json' => 'json'],
        'payroll_run_events' => ['event_type' => 'keep', 'from_status' => 'keep', 'metadata_json' => 'json', 'reason' => 'text', 'to_status' => 'keep'],
        'payroll_run_persons' => ['result_hash' => 'keep', 'result_json' => 'json'],
        'payroll_run_revisions' => ['idempotency_key_hash' => 'keep', 'input_snapshot_hash' => 'keep', 'input_snapshot_json' => 'json', 'result_snapshot_hash' => 'keep', 'result_snapshot_json' => 'json', 'ruleset_manifest_hash' => 'keep', 'schema_version' => 'keep'],
        'payroll_run_validations' => ['code' => 'keep', 'entity_type' => 'keep', 'message' => 'text', 'override_reason' => 'text', 'remediation_path' => 'keep', 'subject_ids_json' => 'keep'],
        'payroll_shifts' => ['series_key' => 'keep', 'timezone_name' => 'keep'],
        'payroll_sickness_cases' => ['additional_note' => 'text', 'care_days' => 'json', 'cared_first_name' => 'first_name', 'cared_last_name' => 'last_name', 'contact_worker_email' => 'email', 'contact_worker_name' => 'person_name', 'contact_worker_phone' => 'phone', 'decision_number' => 'shape', 'long_term_care_refusal_reason' => 'text', 'maternity_care_reason' => 'keep', 'paternity_reason' => 'keep', 'pension_kind' => 'keep', 'rejection_reason' => 'text', 'relationship_code' => 'keep', 'return_reason' => 'text', 'school_business_id' => 'ico', 'school_name' => 'party_name'],
        'payroll_sickness_compensation_segments' => ['trace' => 'json'],
        'payroll_sickness_events' => ['calculation_trace' => 'json', 'ruleset_hash' => 'keep', 'ruleset_id' => 'keep'],
        'payroll_sickness_input_materializations' => ['source_snapshot_hash' => 'keep', 'source_snapshot_json' => 'json'],
        'payroll_statutory_accumulator_entries' => ['record_hash' => 'keep', 'source_result_hash' => 'keep', 'values_json' => 'keep'],
        'payroll_statutory_accumulator_openings' => ['evidence_json' => 'json', 'idempotency_key_hash' => 'keep', 'record_hash' => 'keep', 'source_reference' => 'text', 'values_json' => 'keep'],
        'payroll_statutory_obligation_evidence' => ['attestation_version' => 'keep', 'capability_matrix_sha256' => 'keep', 'capability_matrix_version' => 'keep', 'case_reference' => 'text', 'document_sha256' => 'keep', 'idempotency_key_hash' => 'keep', 'payment_currency' => 'keep', 'receipt_reference' => 'text', 'request_fingerprint' => 'keep'],
        'payroll_statutory_person_results' => ['input_snapshot_hash' => 'keep', 'input_snapshot_json' => 'json', 'result_snapshot_hash' => 'keep', 'result_snapshot_json' => 'json'],
        'payroll_statutory_relationship_results' => ['input_snapshot_hash' => 'keep', 'input_snapshot_json' => 'json', 'result_snapshot_hash' => 'keep', 'result_snapshot_json' => 'json'],
        'payroll_statutory_results' => ['input_snapshot_hash' => 'keep', 'input_snapshot_json' => 'json', 'result_set_hash' => 'keep', 'result_snapshot_hash' => 'keep', 'result_snapshot_json' => 'json', 'ruleset_hash' => 'keep', 'ruleset_id' => 'keep', 'schema_version' => 'keep'],
        'payroll_submission_artifacts' => ['artifact_sha256' => 'keep', 'catalog_version' => 'keep', 'content_ciphertext' => 'wipe', 'idempotency_key_hash' => 'keep', 'mime_type' => 'keep', 'xsd_version' => 'keep'],
        'payroll_submission_deadlines' => ['ruleset_hash' => 'keep', 'ruleset_id' => 'keep', 'trigger_event_hash' => 'keep'],
        'payroll_submission_inbox_items' => ['snooze_reason' => 'text', 'source_key_hash' => 'keep'],
        'payroll_submission_issues' => ['details_ciphertext' => 'wipe', 'details_hash' => 'keep', 'entity_reference' => 'text', 'entity_type' => 'keep', 'issue_code' => 'keep'],
        'payroll_submission_parts' => ['agenda_code' => 'keep', 'part_reference' => 'text', 'source_entity_reference' => 'text', 'source_entity_type' => 'keep', 'source_snapshot_hash' => 'keep', 'subject_reference' => 'text'],
        'payroll_submission_receipts' => ['correlation_reference' => 'keep', 'idempotency_key_hash' => 'keep', 'protocol_code' => 'keep', 'receipt_reference' => 'keep', 'request_fingerprint' => 'keep', 'summary_hash' => 'keep'],
        'payroll_submission_signing_profiles' => ['cssz_registered_serial' => 'keep'],
        'payroll_submission_transport_attempts' => ['close_error' => 'text', 'correlation_reference' => 'keep', 'error_code' => 'keep', 'error_message' => 'text', 'idempotency_key_hash' => 'keep', 'last_poll_error' => 'text', 'request_sha256' => 'keep'],
        'payroll_submissions' => ['correlation_reference' => 'keep', 'idempotency_key_hash' => 'keep', 'request_fingerprint' => 'keep', 'source_snapshot_hash' => 'keep'],
        'payroll_surcharge_input_materializations' => ['evidence_hash' => 'keep', 'source_snapshot_hash' => 'keep', 'source_snapshot_json' => 'json'],
        'payroll_takeover_payment_evidence' => ['currency_code' => 'keep', 'external_person_ref' => 'text'],
        'payroll_taxable_income_confirmation_requests' => ['note' => 'text'],
        'payroll_takeover_runs' => ['input_snapshot_hash' => 'keep', 'input_snapshot_json' => 'json', 'result_snapshot_hash' => 'keep', 'result_snapshot_json' => 'json', 'takeover_sources' => 'keep'],
        'payroll_time_entries' => ['series_key' => 'keep', 'source_hash' => 'keep', 'source_reference' => 'text', 'timezone_name' => 'keep'],
        'payroll_time_import_errors' => ['error_code' => 'keep', 'error_message' => 'text', 'field_name' => 'keep', 'row_hash' => 'keep'],
        'payroll_time_imports' => ['content_hash' => 'keep', 'original_name' => 'file_name'],
        'payroll_time_month_events' => ['jmhz_work_summary_hash' => 'keep', 'reason' => 'text', 'snapshot_hash' => 'keep'],
        'payroll_time_month_import_summaries' => ['content_sha256' => 'keep', 'sources_json' => 'json', 'values_json' => 'keep'],
        'payroll_time_months' => ['reopen_reason' => 'text'],
        'payroll_travel_compensation_links' => ['source_reference' => 'text', 'source_system' => 'keep'],
        'payroll_wage_statement_revisions' => ['snapshot_hash' => 'keep', 'snapshot_json' => 'json', 'source_manifest_hash' => 'keep'],
        'payroll_warning_suppressions' => ['code' => 'keep', 'reason' => 'text'],
        'payroll_work_calendars' => ['name' => 'text', 'timezone_name' => 'keep', 'week_pattern' => 'keep'],
        'pdf_signature_output_settings' => ['backend' => 'keep', 'output_type' => 'keep', 'signature_config_json' => 'json'],
        'abra_flexi_import_map' => ['kind' => 'keep', 'abra_key' => 'text', 'target_type' => 'keep', 'source_hash' => 'keep'],
        'abra_flexi_imports' => ['automation_snapshot' => 'json', 'protocol' => 'json'],
        'pohoda_import_map' => ['kind' => 'keep', 'pohoda_key' => 'text'],
        'pohoda_imports' => ['agenda_ico' => 'ico', 'automation_snapshot' => 'json', 'export_sha256' => 'keep', 'pohoda_version' => 'keep', 'protocol' => 'json'],
        'posting_rules' => ['credit_account_code' => 'keep', 'debit_account_code' => 'keep', 'description' => 'text', 'rule_key' => 'keep'],
        'premier_import_map' => ['kind' => 'keep', 'premier_key' => 'text'],
        'premier_imports' => ['agenda_ico' => 'ico', 'automation_snapshot' => 'json', 'backup_sha256' => 'keep', 'program_version' => 'keep', 'protocol' => 'json'],
        'price_list_customer_overrides' => ['currency_code' => 'keep'],
        'price_list_item_prices' => ['currency_code' => 'keep'],
        'price_list_items' => ['base_currency_code' => 'keep', 'code' => 'keep', 'description' => 'text', 'name' => 'text', 'unit' => 'keep'],
        'product_assemblies' => ['components_json' => 'json', 'definition_json' => 'json', 'operation_key' => 'keep', 'request_hash' => 'keep'],
        'product_master_i18n' => ['description' => 'keep', 'locale' => 'keep', 'name' => 'keep', 'seo_description' => 'keep', 'seo_title' => 'keep', 'short_desc' => 'keep'],
        'product_masters' => ['name' => 'keep'],
        'product_set_revisions' => ['definition_json' => 'keep'],
        'product_sets' => ['definition_json' => 'keep'],
        'product_variant_i18n_inheritance' => ['locale' => 'keep'],
        'product_variants' => ['option_signature' => 'keep'],
        'project_billing_emails' => ['email' => 'email', 'label' => 'text', 'usages' => 'keep'],
        'projects' => ['contract_number' => 'keep', 'name' => 'text', 'note' => 'text', 'project_number' => 'keep'],
        'public_holidays' => ['code' => 'keep', 'month_day' => 'keep', 'name' => 'keep', 'note' => 'keep'],
        'purchase_invoice_approvals' => ['comment' => 'text', 'token_hash' => 'token'],
        'purchase_invoice_counters' => ['period' => 'keep'],
        'purchase_invoice_items' => ['description' => 'text', 'expense_account_code' => 'keep', 'unit' => 'keep', 'vat_classification_code' => 'keep'],
        'purchase_invoice_inbox_dismissed' => ['sha256' => 'keep', 'vendor_invoice_number' => 'keep'],
        'purchase_invoice_submissions' => ['document_sha256' => 'keep', 'extraction_error' => 'text', 'extraction_source' => 'keep', 'note' => 'text', 'status_reason' => 'text'],
        'purchase_invoice_vat_allocations' => ['account_code' => 'keep', 'description' => 'text', 'vat_classification_code' => 'keep'],
        'purchase_invoices' => ['card_last4' => 'card_last4', 'external_barcode' => 'keep', 'extraction_review' => 'json', 'extraction_warning' => 'text', 'import_batch_id' => 'keep', 'note_above_items' => 'text', 'note_below_items' => 'text', 'own_snapshot' => 'json', 'payment_account_number' => 'bank_account', 'payment_bank_code' => 'keep', 'payment_bic' => 'keep', 'payment_constant_symbol' => 'keep', 'payment_iban' => 'iban', 'payment_variable_symbol' => 'symbol', 'pdf_hash' => 'keep', 'pdf_original_name' => 'file_name', 'pdf_path' => 'file_path', 'source_hash' => 'keep', 'source_original_name' => 'file_name', 'source_path' => 'file_path', 'varsymbol' => 'symbol', 'vat_classification_code' => 'keep', 'vat_overrides' => 'json', 'vendor_invoice_number' => 'keep', 'vendor_snapshot' => 'json'],
        'purchase_order_lines' => ['description' => 'text', 'note' => 'text', 'unit' => 'keep', 'vendor_sku' => 'keep'],
        'purchase_orders' => ['cancel_reason' => 'text', 'close_reason' => 'text', 'internal_note' => 'text', 'note' => 'text', 'order_number' => 'keep', 'vendor_reference' => 'keep'],
        'recurring_invoice_template_items' => ['catalog_policy' => 'keep', 'catalog_price_source' => 'keep', 'catalog_source_currency_code' => 'keep', 'description' => 'text', 'description_source' => 'keep', 'oss_consumer_country' => 'keep', 'oss_rate_type' => 'keep', 'revenue_account_code' => 'keep', 'unit' => 'keep', 'vat_classification_code' => 'keep'],
        'recurring_invoice_templates' => ['last_error' => 'text', 'name' => 'text', 'note_above_items' => 'text', 'note_below_items' => 'text', 'payment_variable_symbol' => 'symbol'],
        'remittance_map' => ['account_number' => 'keep', 'account_prefix' => 'keep', 'bank_code' => 'keep', 'label_cs' => 'keep', 'operation_type' => 'keep', 'rule_key' => 'keep'],
        'retention_holds' => ['description' => 'text'],
        'revenue_categories' => ['code' => 'keep', 'credit_note_number_format' => 'keep', 'invoice_number_format' => 'keep', 'label' => 'text', 'proforma_number_format' => 'keep'],
        'role_permissions' => ['permission_key' => 'keep'],
        'roles' => ['name' => 'keep', 'system_key' => 'keep'],
        'sales_order_fulfillment_links' => ['consumed_json' => 'keep'],
        'sales_order_lines' => ['component_snapshot' => 'json', 'description' => 'text', 'line_uuid' => 'keep', 'product_snapshot' => 'json', 'sku_snapshot' => 'keep', 'unit' => 'keep'],
        'sales_order_operation_keys' => ['idempotency_key' => 'keep', 'operation' => 'keep', 'result_json' => 'json'],
        'sales_order_returns' => ['lines_json' => 'json', 'return_uuid' => 'keep'],
        'sales_orders' => ['currency_code' => 'keep', 'customer_snapshot' => 'json', 'discount_snapshot' => 'json', 'external_id' => 'keep', 'external_source' => 'keep', 'order_number' => 'keep', 'order_uuid' => 'keep', 'shipping_snapshot' => 'json'],
        'sample_data_entries' => ['entity_type' => 'keep'],
        'saved_filters' => ['name' => 'text', 'page_key' => 'keep', 'payload' => 'json'],
        'scan_batch_items' => ['error' => 'text', 'file_name' => 'file_name', 'sha256' => 'keep'],
        'scan_matches' => ['note' => 'text', 'target_type' => 'keep'],
        'shoptet_import_batches' => ['file_name' => 'file_name', 'invoice_batch_id' => 'keep', 'payload' => 'blob_text', 'payload_sha256' => 'keep', 'report_json' => 'json', 'summary_json' => 'json'],
        'shoptet_orders' => ['content_hash' => 'keep', 'review_reasons' => 'json', 'shoptet_code' => 'keep', 'shoptet_status' => 'keep', 'vat_snapshot' => 'json'],
        'shoptet_settings' => ['feed_etag' => 'keep', 'feed_token_hash' => 'wipe', 'last_fetch_message' => 'text', 'order_url_enc' => 'wipe', 'order_url_hint' => 'wipe'],
        'signature_document_overrides' => ['entity_type' => 'keep'],
        'signature_role_profiles' => ['output_type' => 'keep'],
        'signature_user_profiles' => ['output_type' => 'keep'],
        'signing_credentials' => ['certificate_email' => 'email', 'certificate_fingerprint' => 'keep', 'certificate_path' => 'file_path', 'certificate_subject' => 'text', 'certificate_usage_json' => 'keep', 'encrypted_passphrase' => 'wipe', 'passphrase_profile_id' => 'keep'],
        'signing_profiles' => ['allowed_usages_json' => 'keep', 'code' => 'keep', 'default_backend' => 'keep', 'name' => 'text', 'pdf_reason' => 'text', 'pdf_tsa_password_enc' => 'wipe', 'pdf_tsa_url' => 'keep', 'pdf_tsa_username' => 'login'],
        'small_assets' => ['disposal_reason' => 'text', 'document_ref' => 'keep', 'inventory_number' => 'keep', 'location' => 'text', 'name' => 'text', 'notes' => 'text', 'responsible_person' => 'person_name', 'vendor_name' => 'party_name'],
        'statement_account_map' => ['account_prefix' => 'keep', 'row_code' => 'keep'],
        'statement_account_overrides' => ['account_prefix' => 'keep', 'follows_prefix' => 'keep', 'note' => 'text', 'row_code' => 'keep'],
        'statement_function_map' => ['account_prefix' => 'keep', 'note' => 'text'],
        'statement_notes' => ['content' => 'text', 'section_key' => 'keep'],
        'statement_rows' => ['calc_key' => 'keep', 'label' => 'keep', 'parent_row_code' => 'keep', 'row_code' => 'keep'],
        'statement_versions' => ['version_code' => 'keep'],
        'stereo_nx_import_map' => ['kind' => 'keep', 'source_hash' => 'keep', 'source_ico' => 'ico', 'source_key' => 'text'],
        'stock_attribute_i18n' => ['label' => 'keep', 'locale' => 'keep'],
        'stock_attribute_options' => ['code' => 'keep', 'label' => 'keep'],
        'stock_attributes' => ['code' => 'keep', 'name' => 'keep', 'unit' => 'keep'],
        'stock_categories' => ['code' => 'keep', 'expense_account_code' => 'keep', 'name' => 'keep', 'path' => 'keep', 'revenue_account_code' => 'keep'],
        'stock_category_i18n' => ['description' => 'keep', 'locale' => 'keep', 'name' => 'keep', 'seo_slug' => 'keep'],
        'stock_currencies' => ['code' => 'keep', 'name' => 'keep', 'symbol' => 'keep'],
        'stock_cycle_counts' => ['note' => 'text'],
        'stock_document_lines' => ['note' => 'text', 'source_description' => 'text', 'tracking_input_json' => 'json'],
        'stock_documents' => ['description' => 'text', 'doc_number' => 'keep', 'partner_name' => 'party_name'],
        'stock_fee_types' => ['code' => 'keep', 'name' => 'keep'],
        'stock_item_attribute_values' => ['value_text' => 'keep'],
        'stock_item_customer_prices' => ['currency_code' => 'keep', 'note' => 'text'],
        'stock_item_fees' => ['currency_code' => 'keep'],
        'stock_item_i18n' => ['description' => 'keep', 'locale' => 'keep', 'name' => 'keep', 'seo_description' => 'keep', 'seo_slug' => 'keep', 'seo_title' => 'keep', 'short_desc' => 'keep'],
        'stock_item_prices' => ['computed_calculation_mode' => 'keep', 'computed_context' => 'keep', 'computed_cost_source' => 'keep', 'computed_rate_source' => 'keep', 'currency_code' => 'keep'],
        'stock_item_promo_prices' => ['currency_code' => 'keep', 'label' => 'keep', 'note' => 'text'],
        'stock_item_templates' => ['content_json' => 'keep', 'name' => 'keep'],
        'stock_item_units' => ['ean' => 'keep', 'unit_code' => 'keep'],
        'stock_item_vendors' => ['currency_code' => 'keep', 'note' => 'text', 'vendor_sku' => 'keep'],
        'stock_items' => ['default_sale_unit' => 'keep', 'ean' => 'keep', 'expense_account_code' => 'keep', 'intrastat_cn8_code' => 'keep', 'intrastat_country_of_origin' => 'keep', 'intrastat_supplementary_unit' => 'keep', 'name' => 'keep', 'note' => 'text', 'revenue_account_code' => 'keep', 'sku' => 'keep', 'unit' => 'keep'],
        'stock_landed_costs' => ['description' => 'text'],
        'stock_locales' => ['code' => 'keep', 'name' => 'keep'],
        'stock_media' => ['alt_text' => 'keep', 'mime_type' => 'keep', 'original_name' => 'file_name', 'storage_key' => 'keep', 'title' => 'keep'],
        'stock_packaging_units' => ['code' => 'keep', 'name' => 'keep'],
        'stock_price_level_rules' => ['currency_code' => 'keep'],
        'stock_price_levels' => ['code' => 'keep', 'name' => 'keep'],
        'stock_pricing_exchange_rates' => ['currency_code' => 'keep', 'source' => 'keep'],
        'stock_pricing_profiles' => ['code' => 'keep', 'currency_code' => 'keep', 'fx_source' => 'keep', 'name' => 'keep'],
        'stock_tags' => ['code' => 'keep', 'color' => 'keep', 'name' => 'keep'],
        'stock_takes' => ['counting_method' => 'keep', 'note' => 'text', 'responsible_count_name' => 'person_name', 'responsible_inventory_name' => 'person_name'],
        'stock_tracking_units' => ['lot_code' => 'keep', 'serial_number' => 'keep', 'tracking_key' => 'keep'],
        'stock_valuation_rows' => ['cursor_json' => 'keep'],
        'submission_channel_credentials' => ['box_id' => 'data_box', 'certificate_ciphertext' => 'wipe', 'certificate_fingerprint' => 'keep', 'certificate_passphrase_ciphertext' => 'wipe', 'label' => 'text'],
        'submission_defect_notices' => ['note' => 'text', 'notice_reference' => 'keep'],
        'submission_inbox_messages' => ['delivery_note' => 'text', 'external_message_id' => 'keep', 'raw_sha256' => 'keep', 'sender_box_id' => 'data_box', 'sender_ident' => 'shape', 'sender_name' => 'party_name', 'subject' => 'text'],
        'submission_inbox_polls' => ['last_error_code' => 'keep', 'last_error_message' => 'text'],
        'submission_inbox_purge_manifest' => ['internal_filename' => 'file_path', 'last_error' => 'text', 'sha256' => 'keep', 'thumb_filename' => 'file_path'],
        'submission_isds_mobile_credentials' => ['communication_code_ciphertext' => 'wipe', 'username_ciphertext' => 'wipe'],
        'submission_outbox' => ['acceptance_note' => 'text', 'agenda_code' => 'keep', 'artifact_filename' => 'file_name', 'artifact_sha256' => 'keep', 'correlation_reference' => 'keep', 'external_message_id' => 'keep', 'idempotency_key_hash' => 'keep', 'last_error_code' => 'keep', 'last_error_message' => 'text', 'recipient_box_id' => 'keep', 'subject' => 'text'],
        'submission_outbox_attempts' => ['correlation_reference' => 'keep', 'error_code' => 'keep', 'error_message' => 'text', 'external_message_id' => 'keep', 'request_sha256' => 'keep'],
        'submission_recipients' => ['address' => 'keep', 'business_id' => 'keep', 'code' => 'keep', 'isds_box_id' => 'keep', 'name' => 'keep', 'source_note' => 'keep', 'source_url' => 'keep'],
        'supplier' => ['abo_client_number' => 'shape', 'ai_assist_scope' => 'keep', 'ai_dpa_confirmations' => 'json', 'ai_extraction_notes' => 'text', 'ai_pseudo_salt' => 'token', 'anthropic_api_key_enc' => 'wipe', 'anthropic_default_model' => 'keep', 'azure_openai_api_key_enc' => 'wipe', 'azure_openai_api_version' => 'keep', 'azure_openai_deployment' => 'keep', 'azure_openai_endpoint' => 'wipe', 'city' => 'city', 'commercial_register' => 'shape_digits', 'company_name' => 'party_name', 'credit_note_number_format' => 'keep', 'cssz_ossz_code' => 'keep', 'cssz_vsdp' => 'shape', 'cz_nace_code' => 'keep', 'data_box_id' => 'data_box', 'data_box_type' => 'keep', 'default_note_below_items_cs' => 'text', 'default_note_below_items_en' => 'text', 'dic' => 'dic', 'display_name' => 'party_name', 'email' => 'email', 'email_accent_color' => 'keep', 'epo_taxpayer_code' => 'keep', 'fakturoid_access_token_enc' => 'wipe', 'fakturoid_api_key_enc' => 'wipe', 'fakturoid_client_id' => 'wipe', 'fakturoid_client_secret_enc' => 'wipe', 'fakturoid_email' => 'email', 'fakturoid_slug' => 'wipe', 'financial_office_code' => 'keep', 'gemini_api_key_enc' => 'wipe', 'gemini_default_model' => 'keep', 'health_insurance_code' => 'keep', 'health_insurance_number' => 'shape', 'ic' => 'ico', 'idoklad_access_token' => 'wipe', 'idoklad_client_id' => 'wipe', 'idoklad_client_secret_enc' => 'wipe', 'invoice_number_format' => 'keep', 'logo_path' => 'file_path', 'ollama_api_key_enc' => 'wipe', 'ollama_base_url' => 'wipe', 'ollama_default_model' => 'keep', 'openai_api_key_enc' => 'wipe', 'openai_base_url' => 'keep', 'openai_default_model' => 'keep', 'opr_jmeno' => 'first_name', 'opr_postaveni' => 'keep', 'opr_prijmeni' => 'last_name', 'oss_identification_country' => 'keep', 'oss_return_currency' => 'keep', 'phone' => 'phone', 'pohoda_account_code' => 'keep', 'pohoda_accounting_code' => 'keep', 'pohoda_activity_code' => 'keep', 'pohoda_centre_code' => 'keep', 'pohoda_contract_code' => 'keep', 'proforma_number_format' => 'keep', 'purchase_invoice_number_format' => 'keep', 'self_copy' => 'json', 'sest_email' => 'email', 'sest_funkce' => 'keep', 'sest_jmeno' => 'first_name', 'sest_prijmeni' => 'last_name', 'sest_telefon' => 'phone', 'signature_path' => 'file_path', 'street' => 'street', 'street_number_orient' => 'keep', 'street_number_pop' => 'keep', 'tagline' => 'text', 'tax_accounting_decree' => 'keep', 'tax_entity_status' => 'keep', 'web' => 'web', 'workplace_code' => 'keep', 'zip' => 'zip'],
        'supplier_bank_accounts' => ['account_canonical' => 'account_key', 'account_number' => 'bank_account', 'analytic_suffix' => 'keep', 'bank_code' => 'keep', 'bank_code_norm' => 'keep', 'currency' => 'keep', 'document_series' => 'keep', 'iban' => 'iban', 'label' => 'text'],
        'supplier_domains' => ['hostname' => 'host', 'verification_error' => 'text', 'verification_token' => 'token'],
        'supplier_groups' => ['name' => 'text'],
        'supplier_osvc_month_statuses' => ['note' => 'text'],
        'supplier_tax_representation_history' => ['note' => 'text', 'representative_company_name' => 'party_name', 'representative_ev_number' => 'shape', 'representative_first_name' => 'first_name', 'representative_ico' => 'ico', 'representative_last_name' => 'last_name'],
        'supplier_vat_status_history' => ['note' => 'text'],
        'tax_advance_overrides' => ['note' => 'text'],
        'tax_advance_schedules' => ['variable_symbol' => 'symbol'],
        'tax_constants' => ['data' => 'keep'],
        'tax_evidence_closings' => ['checklist' => 'json', 'closing_balances' => 'keep', 'opening_balances' => 'keep', 'source_hash' => 'keep', 'source_snapshot' => 'json', 'unsupported_cases' => 'json'],
        'tax_evidence_non_cash_adjustments' => ['description' => 'text', 'evidence_ref' => 'text'],
        'tax_profile_activities' => ['allocation_note' => 'text', 'nace_code' => 'keep', 'name' => 'text'],
        'tax_profile_children' => ['birth_number' => 'birth_number', 'evidence_ref' => 'text', 'first_name' => 'first_name', 'last_name' => 'last_name'],
        'tax_profile_spouse_claims' => ['birth_number' => 'birth_number', 'evidence_ref' => 'text', 'first_name' => 'first_name', 'last_name' => 'last_name'],
        'tax_related_party_adjustments' => ['reason' => 'text'],
        'tax_submission_artifacts' => ['sha256' => 'keep', 'verification_json' => 'json'],
        'tax_submission_attempts' => ['confirmation_ciphertext' => 'wipe', 'error_code' => 'keep', 'error_message' => 'text', 'idempotency_key' => 'keep', 'last_response_ciphertext' => 'wipe', 'last_status_json' => 'json', 'offline_password_ciphertext' => 'wipe', 'offline_transfer_id' => 'keep', 'remote_submission_ref' => 'keep', 'request_sha256' => 'keep', 'resolution_code' => 'keep', 'resolution_note' => 'text', 'signing_fingerprint' => 'keep', 'state_password_ciphertext' => 'wipe', 'submitted_signed_ciphertext' => 'wipe', 'test_messages_json' => 'json', 'test_signed_ciphertext' => 'wipe'],
        'tax_submission_status_events' => ['details_json' => 'json', 'event_type' => 'keep', 'status' => 'keep'],
        'tax_submissions' => ['form_code' => 'keep', 'form_variant' => 'keep', 'notes' => 'text', 'submission_ref' => 'keep', 'summary_json' => 'json', 'validation_errors' => 'json', 'xml_content' => 'text', 'xml_sha256' => 'keep'],
        'tax_unpaid_liability_addbacks' => ['note' => 'text'],
        'trip_categories' => ['code' => 'keep', 'label' => 'keep'],
        'trips' => ['destination' => 'city', 'note' => 'text', 'origin' => 'city', 'purpose' => 'text'],
        'units' => ['code' => 'keep', 'label_cs' => 'keep', 'label_en' => 'keep'],
        'user_preferences' => ['payload' => 'json', 'pref_key' => 'keep'],
        'users' => ['email' => 'email', 'last_login_ip' => 'wipe', 'last_login_ua' => 'wipe', 'name' => 'person_name', 'password_hash' => 'password', 'totp_secret' => 'wipe', 'webauthn_user_handle' => 'wipe'],
        'vat_classifications' => ['code' => 'keep', 'dphdp3_line' => 'keep', 'dphdp3_line_secondary' => 'keep', 'kh_bad_debt' => 'keep', 'kh_regime_code' => 'keep', 'kh_section' => 'keep', 'kod_pred_pl' => 'keep', 'label' => 'keep'],
        'vat_clearing_runs' => ['status' => 'keep', 'submission_form' => 'keep', 'submission_variant' => 'keep'],
        'vat_deduction_adjustments' => ['label' => 'text', 'note' => 'text'],
        'vat_rates' => ['code' => 'keep', 'country' => 'keep', 'label_cs' => 'keep', 'label_en' => 'keep'],
        'vat_registration_corrections' => ['label' => 'text', 'note' => 'text'],
        'vat_s43_corrections' => ['corrective_doc_number' => 'keep', 'reason' => 'text'],
        'vat_s46_corrections' => ['corrective_doc_number' => 'keep', 'note' => 'text'],
        'vat_s74b_corrections' => ['note' => 'text'],
        'warehouse_locations' => ['code' => 'keep', 'name' => 'keep'],
        'warehouses' => ['code' => 'keep', 'name' => 'keep', 'note' => 'text'],
        'work_report_items' => ['description' => 'text'],
        'work_report_links' => ['token' => 'token'],
        'work_report_materials' => ['description' => 'text', 'unit' => 'keep'],
        'work_reports' => ['material_title' => 'text', 'title' => 'text'],
    ];

    /** Strategie, které zpracuje první průchod (strukturované hodnoty plní slovník). */
    public const PHASE_STRUCTURED = [
        'party_name', 'person_name', 'first_name', 'last_name', 'street', 'city', 'zip', 'address',
        'ico', 'dic', 'birth_number', 'email', 'phone', 'bank_account', 'iban', 'card_last4',
        'data_box', 'web', 'host', 'login', 'shape', 'shape_digits', 'file_name', 'file_path',
        'wipe', 'token', 'password', 'blob_pdf', 'blob_text',
    ];

    /** Odvozené klíče a symboly — potřebují hotové mapování ze strukturovaného průchodu. */
    public const PHASE_DERIVED = ['account_key', 'symbol'];

    /** Volné texty a JSON — potřebují úplný slovník. */
    public const PHASE_TEXT = ['text', 'json'];

    /** @return list<string> */
    public static function knownStrategies(): array
    {
        return [...self::PHASE_STRUCTURED, ...self::PHASE_DERIVED, ...self::PHASE_TEXT, 'keep', 'sealed_companion'];
    }

    public static function isSealed(string $strategy): bool
    {
        return str_starts_with($strategy, 'sealed:');
    }

    /**
     * @return array{field:string, type_column:?string, hash:string, masked:?string, entity:string}
     */
    public static function parseSealed(string $strategy): array
    {
        $parts = explode(':', $strategy);
        if (count($parts) !== 5 || $parts[0] !== 'sealed') {
            throw new \InvalidArgumentException("Neplatná strategie šifrované hodnoty: {$strategy}");
        }
        $typeColumn = str_starts_with($parts[1], '@') ? substr($parts[1], 1) : null;

        return [
            'field' => $typeColumn === null ? $parts[1] : '',
            'type_column' => $typeColumn,
            'hash' => $parts[2],
            'masked' => $parts[3] === '-' ? null : $parts[3],
            'entity' => $parts[4],
        ];
    }
}
